---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recoveryのこのリリースには、次の既知の制限があります。 
---
= KVM ワークロードに対するNetApp Backup and Recoveryの既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and RecoveryのKVMワークロードに関する現在の制限事項を確認してください。

以下のサポートされていないアクションと構成は、NetApp Backup and Recovery の KVM ワークロードに適用されます：



[[unsupported-actions]]
== サポートされていないアクション

次のアクションはサポートされていません：

* NetApp Console ローカル展開のバックアップとリカバリのプレビューリリースでは、オブジェクトストレージへのバックアップは ONTAP S3 と StorageGRID の宛先のみサポートされています。バックアップのアーカイブは、このプレビューリリースではサポートされていません。
* VM のクローン、マウント、またはアンマウント
* SANに保存されたVMを保護する
* アプリケーションを保護する
* ユーザー定義のバックアップを作成します（ NetApp Consoleから開始されたバックアップのみがサポートされます）




[[unsupported-configurations]]
== サポートされない構成

次の構成はサポートされていません。

* Role-Based Access Control（RBAC;ロールベース アクセス制御）
* KVMホストに直接接続されたディスク
* 複数の NFS マウント ポイントまたは共有にまたがるディスク
* RAWディスクフォーマット
* NetFS以外のストレージプールタイプ（NetFSのみがサポートされます）




[[troubleshooting-notes]]
== トラブルシューティングの注意事項

KVMワークロードでNetApp Backup and Recoveryを使用する場合は、次の点に注意してください。

* QEMUゲストエージェントが保護対象の仮想マシン内で実行されていない場合、バックアップが失敗する可能性があります。この問題を回避するには、バックアップを開始する前に `qemu-guest-agent`デーモンがVM上で実行されていることを確認してください。

