---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery、サービスを使用するためにまずデータを検出する必要があります。検出中に、 NetApp Backup and Recovery は組織内のシステム内のすべてのボリュームとファイルを分析します。 
---
= NetApp Backup and Recovery の SQL Server ワークロードに関する既知の制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery を SQL Server ワークロードに使用する前に、これらの制限事項を確認してください。



[[backup-and-recovery-preview-for-netapp-console-local-deployment-limitation]]
== NetApp Console ローカル展開のバックアップとリカバリのプレビューの制限

NetApp Console ローカル展開のバックアップとリカバリのプレビューリリースでは、オブジェクトストレージへのバックアップは ONTAP S3 と StorageGRID の宛先のみサポートされています。バックアップのアーカイブは、このプレビューリリースではサポートされていません。



[[clone-lifecycle-support]]
== クローンライフサイクルのサポート

* オブジェクト ストレージからのクローン作成はサポートされていません。
* オンデマンドクローンでは一括クローン操作はサポートされていません。
* I グループの選択はサポートされていません。
* QOS (最大スループット) オプションの選択はサポートされていません。




[[standard-deployment-mode-only]]
== 標準展開モードのみ

このNetApp Backup and Recoveryバージョンは、制限モードやプライベート モードではなく、標準展開モードでのみ動作します。



[[windows-cluster-name-restriction]]
== Windows クラスター名の制限

Windows クラスター名にはアンダースコア (_) 文字を含めることはできません。



[[snapcenter-migration-issues]]
== SnapCenterの移行に関する問題

SnapCenterからNetApp Backup and Recoveryへのリソースの移行には、次の制限があります。

SnapCenterポリシーをNetApp Backup and Recoveryポリシーに移行する方法の詳細については、以下を参照してください。link:reference-policy-differences-snapcenter.html["SnapCenterのポリシーとNetApp Backup and Recovery のポリシーの比較"] 。



[[resource-group-limitations]]
=== リソース グループの制限

リソース グループ内のすべてのリソースが保護されており、そのうちの 1 つのリソースがリソース グループ外でも保護されている場合、 SnapCenterからの移行はブロックされます。

*回避策*: リソースをリソース グループ内またはそれ自体で保護し、両方で保護しないでください。



[[resources-with-multiple-policies-using-the-same-schedule-tier-not-supported]]
=== 同じスケジュール層を使用する複数のポリシーを持つリソースはサポートされていません

同じスケジュール階層（例えば、時間単位、日単位、週単位）を使用する複数のポリシーを、1つのリソースに割り当てることはできません。NetApp Backup and Recoveryでは、SnapCenterからこれらのリソースはインポートされません。

*回避策*: 同じスケジュール層を使用するポリシーを 1 つだけリソースにアタッチします。



[[hourly-policies-must-begin-at-the-start-of-the-hour]]
=== 時間単位のポリシーは時間の開始時に開始する必要があります

1 時間ごとに繰り返すSnapCenterポリシーがあり、時間の開始時に間隔を使用しない場合、 NetApp Backup and Recovery はリソースをインポートしません。たとえば、1:30、2:30、3:30 などのスケジュールを持つポリシーはサポートされていませんが、1:00、2:00、3:00 などのスケジュールを持つポリシーはサポートされています。

*回避策*: 毎時 0 分から 1 時間間隔で繰り返すポリシーを使用します。



[[both-daily-and-monthly-policies-attached-to-one-resource-not-supported]]
=== 1 つのリソースに日次ポリシーと月次ポリシーの両方を適用することはサポートされていません

SnapCenterポリシーが日単位と月単位の両方の間隔で繰り返される場合、NetApp Backup and Recoveryはそのポリシーをインポートしません。

例えば、リソースに日次ポリシー（間隔が7日以下または7日を超えるもの）を関連付けると同時に、同じリソースに月次ポリシーを関連付けることはできません。

*回避策*: 毎日または毎月の間隔を使用するポリシーを使用しますが、両方を使用するポリシーは使用しません。



[[on-demand-backup-policies-not-migrated]]
=== オンデマンドバックアップポリシーは移行されませんでした

NetApp Backup and Recovery は、SnapCenter からオンデマンドバックアップポリシーをインポートしません。



[[log-only-backup-policies-not-migrated]]
=== ログのみのバックアップ ポリシーは移行されません

NetApp Backup and Recovery は、 SnapCenterからログのみのバックアップ ポリシーをインポートしません。  SnapCenterポリシーにログのみのバックアップが含まれている場合、 NetApp Backup and Recovery はリソースをインポートしません。

*回避策*: ログのみのバックアップ以外のバックアップを使用するSnapCenterのポリシーを使用します。



[[host-mapping]]
=== ホストマッピング

SnapCenterはリソース用のストレージ クラスタまたはストレージ VMをホストにマッピングしませんが、NetApp Backup and Recoveryはマッピングします。NetApp Backup and Recoveryのプレビュー バージョンでは、オンプレミスのONTAPクラスタまたはストレージ VMはホストにマッピングされません。さらに、NetApp Consoleはストレージ VMをサポートしていません。

*回避策*: SnapCenterからリソースをインポートする前に、オンプレミスのSnapCenterに登録されているすべてのオンプレミスのONTAPストレージ システム用のシステムをNetApp Backup and Recoveryで作成します。次に、そのクラスターのリソースをSnapCenterからNetApp Backup and Recoveryにインポートします。



[[schedules-not-in-15-minute-intervals]]
=== 15分間隔ではないスケジュール

特定の時間に開始され、15 分間隔以外の間隔で繰り返されるSnapCenterポリシー スケジュールがある場合、 NetApp Backup and Recoveryそのスケジュールはインポートされません。

*回避策*: SnapCenterを使用して、ポリシーが 15 分間隔で繰り返されるように調整します。
