---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery では、サービスを使用するためにまずデータを検出する必要があります。検出中に、 NetApp Backup and Recovery は組織内のシステム内のすべてのボリュームとファイルを分析します。 
---
= Hyper-V ワークロード向けNetApp Backup and Recovery の既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このバージョンで動作しない、または正常に動作しないプラットフォーム、デバイス、または機能がここにリストされています。これらの制限事項を注意深くお読みください。



== サポートされていないアクション

NetApp Backup and Recovery の Hyper-V ワークロードのプライベート プレビュー バージョンでは、次のアクションはサポートされていません。

* リソース グループの作成
* スパニングディスク（複数の CIFS 共有にまたがる）
* SAN経由でVMを保護する
* 保護グループを編集する
* System Center Virtual Machine Manager (SCVMM) を使用してクラスター化された Hyper-V ホストを保護する




== サポートされていないレガシーNetApp Consoleアカウント

従来のNetApp Consoleアカウントは、Hyper-V ワークロードを保護するために必要な機能をサポートしていません。コンソール Web UI でレガシー アカウントを使用しているかどうかを確認します。従来のコンソール アカウントがある場合は、Hyper-V ワークロードを保護する前に新しいアカウントを作成してください。

.手順
. NetApp Consoleメニューから、*管理 > ID とアクセス* を選択します。
. *組織*の下で、組織 ID の横に *アカウント ID* が表示されているかどうかを確認します。
+
*アカウント ID* が表示されている場合は、従来のアカウントを使用しています。

. 従来のアカウントを使用している場合は、次の手順を実行します。
+
.. コンソールからログアウトし、 https://console.netapp.com/["コンソールログインページ"^] 。
.. 新しいアカウントを作成するには、[サインアップ] を選択します。



