---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery のこのリリースには、次の既知の制限があります。 
---
= KVM ワークロードに対するNetAppバックアップおよびリカバリの既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このバージョンで動作しない、または正常に動作しないプラットフォーム、デバイス、または機能がここにリストされています。これらの制限事項を注意深くお読みください。

NetApp Backup and Recovery の KVM ワークロードのプライベート プレビュー バージョンでは、次のアクションと構成はサポートされていません。



== サポートされていないアクション

プライベート プレビュー リリースでは、次のアクションはサポートされていません。

* VM のクローン、マウント、またはアンマウント
* VMを別の場所に復元する
* SANに保存されたVMを保護する
* アプリケーションを保護する
* オブジェクトストアからのバックアップまたは復元
* 保護グループを編集する
* 複数の KVM ホストの VM を使用して保護グループを作成する
* ユーザー定義のバックアップを作成します（ NetAppコンソールから開始されたバックアップのみがサポートされます）




== サポートされない構成

次の構成はサポートされていません。

* Role-Based Access Control（RBAC;ロールベース アクセス制御）
* KVMホストに直接接続されたディスク
* 複数の NFS マウント ポイントまたは共有にまたがるディスク
* RAWディスクフォーマット
* NetFS以外のストレージプールタイプ（NetFSのみがサポートされます）




== サポートされていないレガシーNetApp Consoleアカウント

従来のNetApp Consoleアカウントは、KVM ワークロードを保護するために必要な機能をサポートしていません。コンソール Web UI でレガシー アカウントを使用しているかどうかを確認します。従来のコンソール アカウントがある場合は、KVM ワークロードを保護する前に新しいアカウントを作成してください。

.手順
. NetApp Consoleメニューから、*管理 > ID とアクセス* を選択します。
. *組織*の下で、組織 ID の横に *アカウント ID* が表示されているかどうかを確認します。
+
*アカウント ID* が表示されている場合は、従来のアカウントを使用しています。

. 従来のアカウントを使用している場合は、次の手順を実行します。
+
.. コンソールからログアウトし、 https://console.netapp.com/["コンソールログインページ"^] 。
.. 新しいアカウントを作成するには、[サインアップ] を選択します。



