---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recoveryのこのリリースには、次の既知の制限があります。 
---
= KVM ワークロードに対するNetApp Backup and Recoveryの既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このバージョンで動作しない、または正常に動作しないプラットフォーム、デバイス、または機能がここにリストされています。これらの制限事項を注意深くお読みください。

NetApp Backup and Recoveryの KVM ワークロードのプライベート プレビュー バージョンでは、次のアクションと構成はサポートされていません。



== サポートされていないアクション

プライベート プレビュー リリースでは、次のアクションはサポートされていません。

* VM のクローン、マウント、またはアンマウント
* VMを別の場所に復元する
* SANに保存されたVMを保護する
* アプリケーションを保護する
* ユーザー定義のバックアップを作成します（ NetApp Consoleから開始されたバックアップのみがサポートされます）




== サポートされない構成

次の構成はサポートされていません。

* Role-Based Access Control（RBAC;ロールベース アクセス制御）
* KVMホストに直接接続されたディスク
* 複数の NFS マウント ポイントまたは共有にまたがるディスク
* RAWディスクフォーマット
* NetFS以外のストレージプールタイプ（NetFSのみがサポートされます）




== トラブルシューティングの注意事項

KVMワークロードのプライベートプレビューをNetApp Backup and Recoveryで使用する場合は、次の点に注意してください。

* 保護された VM で QEMU ゲストエージェントが実行されていない場合、バックアップは失敗する可能性があります。回避策として、バックアップを開始する前に VM 上で `qemu-guest-agent`デーモンが実行されていることを確認してください。

