---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: セキュリティを強化するために、NetApp Backup and Recovery で特定のロールのアクセスを設定してください。 
---
= NetApp Backup and Recovery でロールベースのアクセス制御を設定
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console でロールベースアクセス制御（RBAC）を設定して、NetApp Backup and Recovery リソースにアクセスできるユーザーを制御します。RBAC をサポートするワークロードには、管理者ロールまたは閲覧者ロールを割り当てることができます。RBAC をまだサポートしていないワークロードは、プロジェクトレベルまたはフリートレベルの関連付けが利用可能になるまで、Backup and Recovery ロールを持つすべてのユーザーがアクセスできます。


NOTE: NetApp Console はプロジェクトを使用してフォルダー内のリソースを整理しますが、NetApp Console のローカル展開では、プロジェクトをフリートと呼びます。

組織内のリソースへのアクセスを制御するには、NetApp Console の *管理 > ID とアクセス* ページで次の手順を実行します。


NOTE: これらの手順は、NetApp Console で組織管理者ロールが割り当てられていることを前提としています。

.手順
. IDおよびアクセスプロジェクト構造を作成します。
+
組織管理者として、ワークロードを配置するフォルダーとプロジェクト構造を設定します。

. ユーザーロールを割り当てます。
+
.. 主なオプション：
+
ワークロード用に指定された各プロジェクトにユーザーを追加し、適切なロールを付与します。例：

+
*** *Organization admin* および *Backup and Recovery super admin*: これらの役割を持つユーザーは、組織全体のリソースを表示し、Backup and Recovery のワークロードを検出してプロジェクト（たとえば、US East または US West）に割り当てることができます。
*** *フォルダーまたはプロジェクト管理者* および *Backup and Recovery スーパー管理者*：これらの役割を持つユーザーは、割り当てられたフォルダーまたはプロジェクト内のリソースのみを表示できますが、Backup and Recovery ワークロードを検出して、そのプロジェクトに割り当てることができます。


.. 代替オプション：
+
ユーザーに完全な NetApp Backup and Recovery の管理者アクセス権を付与する代わりに、自分自身に NetApp Backup and Recovery のスーパー管理者ロールを割り当てて、ワークロードを直接検出することができます。



. Backup and Recoveryでワークロードを検出します。
+
組織管理者、フォルダ管理者、またはプロジェクト管理者は、利用可能なワークロードを検出し、適切なプロジェクト（米国東部、米国西部など）を選択します。各ワークロードは、選択されたプロジェクトに自動的に関連付けられます。

. プロジェクトにユーザーを追加します。
+
組織管理者、フォルダ管理者、またはプロジェクト管理者が、ワークロードのあるプロジェクトにNetApp Consoleユーザーを追加します。ユーザーのアクセス要件に基づいて、組織閲覧者ロールとBackup and Recoveryロールを割り当ててください。適切なBackup and Recoveryロールを持つユーザーは、これらのプロジェクト内の新しいワークロードに自動的にアクセスできるようになります。





[[related-information]]
== 関連情報

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["NetApp Console の ID とアクセス管理について説明します"^].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp ConsoleのNetApp Backup and Recoveryの役割"^].

