---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery、ワークロードを保護するために、まずワークロードを検出する必要があります。 
---
= NetApp Backup and RecoveryでOracle Databaseワークロードを検出
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracleデータベースを検出すると、NetApp Backup and Recoveryでバックアップとスナップショットを作成およびリストアして保護できるようになります。

*必要なコンソール ロール* バックアップとリカバリのスーパー管理者。詳細はこちらlink:reference-roles.html["バックアップとリカバリの役割と権限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。



== Oracle Databaseホストを追加してリソースを検出する

Oracle ホスト情報を追加し、 NetApp Backup and Recovery でワークロードを検出できるようにします。各コンソール エージェント内で、ワークロードを検出するシステムを選択します。

.手順
. NetApp Consoleメニューから、*保護 > バックアップとリカバリ* を選択します。
. *ワークロード*の下で、*Oracle*タイルを選択します。
+
初めて Backup and Recovery にログインし、コンソールにシステムがあるがリソースが検出されていない場合は、[新しいNetApp Backup and Recovery へようこそ] ページが表示され、[リソースの検出] オプションが表示されます。

. *リソースの検出*を選択します。
. *ワークロード タイプ* フィールドで *Oracle* を選択します。
. この Oracle Database ホストの資格情報をまだ保存していない場合は、*資格情報の追加*を選択します。
+
.. このホストで使用するコンソール エージェントを選択します。
.. この資格情報の名前を入力します。
.. アカウントのユーザー名とパスワードを入力します。
.. *完了*を選択します。


. *ホスト登録*：新しい Oracle Database ホストを追加します。ホストの FQDN または IP アドレス、クレデンシャル、Console エージェント、およびポート番号を入力します。
. （オプション）非ルート ユーザーの資格情報を選択する場合は、次の手順を実行します：
+
.. 選択した非 root ユーザーを Oracle Database ホストの sudoers ファイルに追加する方法については、*sudoers の構成*を選択してください。
.. ダイアログの指示に従い、完了したらチェックボックスを有効にして、*Done* を選択します。


. *詳細設定*：次の操作を行います。
+
.. 使用するポートとインストールパスを入力しますNetAppプラグイン。このプラグインは、Oracle Database ホストとNetApp Backup and Recovery 間の通信を可能にします。
.. NetApp Backup and Recovery でプラグインを自動的にインストールするか、インストールをスキップするか（ホスト上でプラグインを手動でインストールする必要があります）を選択します。
.. インストール前のチェックを実行するか、スキップするかを選択します。


. *Discover*を選択します。
+

TIP: このプロセスには数分かかる場合があります。



.結果
Oracle Database ワークロードは、インベントリ ページのワークロード リストに表示されます。



== NetApp Backup and Recoveryダッシュボードに進みます

. NetApp Consoleメニューから、*保護* > *バックアップとリカバリ* を選択します。
. ワークロード タイル (Microsoft SQL Server など) を選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。

