---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery では、ワークロードを保護するために、まずワークロードを検出する必要があります。 
---
= NetAppバックアップおよびリカバリで Oracle ワークロードを発見
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery では、まず Oracle データベースを検出して保護する必要があります。

*必要なコンソール ロール* バックアップとリカバリのスーパー管理者。学ぶlink:reference-roles.html["バックアップとリカバリの役割と権限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetAppコンソールのアクセスロールについて学習します"^] 。



== Oracleホストを追加してリソースを検出する

Oracle ホスト情報を追加し、 NetApp Backup and Recovery でワークロードを検出できるようにします。各コンソール エージェント内で、ワークロードを検出するシステムを選択します。

.手順
. NetAppコンソール メニューから、*保護 > バックアップとリカバリ* を選択します。
. Oracle タイルで、*検出と管理*を選択します。
+
バックアップおよびリカバリに初めてログインする場合、コンソールにはすでにシステムがあるが、リソースがまだ検出されていない場合は、「新しいNetApp Backup and Recoveryへようこそ」ランディング ページが表示され、*リソースの検出*オプションが表示されます。

. *リソースの検出*を選択します。
. 次の情報を入力してください。
+
.. *ワークロード タイプ*: *Oracle* を選択します。
.. この Oracle ホストの資格情報をまだ保存していない場合は、「資格情報の追加」を選択します。
+
... このホストで使用するコンソール エージェントを選択します。
... この資格情報の名前を入力します。
... アカウントのユーザー名とパスワードを入力します。
... *完了*を選択します。


.. *ホスト登録*: 新しい Oracle ホストを追加します。ホストの FQDN または IP アドレス、資格情報、コンソール エージェント、およびポート番号を入力します。


. *Discover*を選択します。
+

TIP: このプロセスには数分かかる場合があります。



.結果
Oracle ワークロードは、インベントリ ページのワークロード リストに表示されます。



== NetAppバックアップおよびリカバリダッシュボードに進みます

. NetAppバックアップおよびリカバリ ダッシュボードを表示するには、上部のメニューから *ダッシュボード* を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。

