---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery、 Hyper-V 仮想マシンを保護する前に、それらを検出する必要があります。 
---
= NetApp Backup and Recoveryで Hyper-V ワークロードを発見
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery で Hyper-V 仮想マシンを検出し、保護ポリシーを使用して保護できるようにします。

*必須 NetApp コンソールロール* バックアップおよびリカバリのスーパー管理者。link:reference-roles.html["バックアップとリカバリの役割と権限"] について学ぶ。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]。



[[add-a-hyper-v-host-and-discover-resources]]
== Hyper-Vホストを追加してリソースを検出する

Hyper-V ホスト情報を追加して、NetApp Backup and Recovery が仮想マシンを検出できるようにします。各コンソールエージェント内で、リソースを検出するシステムを選択します。


NOTE: Hyper-V ホストを追加してリソースを検出すると、 NetApp Backup and Recoveryによって、仮想マシンの管理と保護を支援するために、Hyper-V ホストにNetApp Hyper-V プラグインとNetApp SnapCenter Windows FileSystem プラグインがインストールされます。

.手順
. NetApp Console メニューから、*Protection* > *Backup and Recovery* を選択します。
+
初めて NetApp Backup and Recovery にログインする場合で、コンソールにシステムが既に存在するがリソースがまだ検出されていない場合、「新しい NetApp Backup and Recovery へようこそ」ランディングページが表示され、*リソースの検出* オプションが表示されます。

. *リソースの検出*を選択します。
. 次の情報を入力してください。
+
.. *ワークロードの種類*: *Hyper-V* を選択します。
.. この Hyper-V ホストの資格情報をまだ保存していない場合は、[資格情報の追加] を選択します。
+
... このホストで使用するコンソール エージェントを選択します。
... この資格情報の名前を入力します。
... アカウントのユーザー名とパスワードを入力します。
... *完了*を選択します。


.. *ホスト登録*：ホストのFQDNまたはIPアドレス、資格情報、コンソールエージェント、ポート番号を入力して、新しいHyper-Vホストを追加します。コンソールエージェントがFQDNを解決できない場合は、代わりにIPアドレスを使用してください。フェイルオーバークラスタの場合は、クラスタ管理IPアドレスを入力してください。


. *Discover*を選択します。
+

TIP: このプロセスには数分かかる場合があります。



.結果
NetApp Backup and Recovery がリソースを検出すると、インベントリ ページのワークロード リストに Hyper-V ワークロードが表示されます。



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== NetApp Backup and Recoveryダッシュボードに進みます

.手順
. NetApp Console メニューから、*Protection* > *Backup and Recovery* を選択します。
. Hyper-Vワークロードタイルを選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。

