---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery、サービスを使用するために、まずワークロードを検出する必要があります。 
---
= NetApp Backup and Recoveryで Kubernetes ワークロードを発見
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery、 Kubernetes ワークロードを保護する前に検出する必要があります。

*必須 NetApp コンソールロール* バックアップおよびリカバリのスーパー管理者。Cloud Volumes ONTAP クラスターに保存されているデータを保護する場合は、Cloud Volumes ONTAP 管理者ロールも必要です。詳細については、link:reference-roles.html["バックアップとリカバリの役割と権限"]を参照してください。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]



[[discover-kubernetes-workloads]]
== Kubernetes ワークロードを発見する

NetApp Backup and Recoveryのインベントリで、環境内のKubernetesワークロードを検出します。ワークロードを追加すると、KubernetesクラスターがNetApp Backup and Recoveryに追加されます。その後、アプリケーションを追加してクラスターリソースを保護できます。必要に応じて、NetApp Consoleのローカル展開を使用して、エアギャップされたローカルのKubernetesリソースを検出することもできます。

[NOTE]
====
現在Trident Protectで保護されているクラスタを検出すると、Trident Protectで使用されていたバックアップスケジュールは検出プロセス中に無効になります（Trident Protectのバックアップスケジュールはバックアップおよびリカバリと互換性がありません）。クラスタのアプリケーションを保護するには、link:br-use-policies-create.html["新しい保護ポリシーを作成する"]または、アプリケーションを既存のポリシーに関連付けます。その後、必要に応じてTrident Protectのバックアップスケジュールを削除できます。

====
.手順
. 次のいずれかを実行します。
+
** Kubernetes ワークロードを初めて検出する場合は、 NetApp Backup and Recovery の*ワークロード* で、*Kubernetes* タイルを選択します。
** Kubernetes ワークロードをすでに検出している場合は、 NetApp Backup and Recoveryで *インベントリ* > *ワークロード* を選択し、*リソースの検出* を選択します。


. *Kubernetes* ワークロード タイプを選択します。
. クラスター名を入力し、クラスターで使用するコンソールエージェントを選択してください。
+
Backup and Recoveryでは、選択したインストール タイプの選択に応じて異なる手順が提供されます。NetApp Consoleのローカル展開を使用する場合は、外部ネットワークに接続されていないエアギャップ環境のリソースを検出できる手順を選択できます。

. Kubernetes クラスターに Trident Protect をインストールする手順を確認するには、インストール タイプの選択を選択してください：
+
** 外部ネットワーク接続を持つクラスターを検出するには、*接続済み*を選択してください。
** 外部ネットワークに接続されていないクラスターを検出するには、*エアギャップ*を選択してください。
+
[role="tabbed-block"]
====
.接続済みの検出
--
... Backup and Recovery に表示されるコマンドラインの手順に従ってください。これらの手順により、Backup and Recovery がクラスターと連携できるようになります。


--
.エアギャップ検出
--
... プライベート Docker コンテナレジストリの URL を入力してください。このレジストリは、インストール中に Trident Protect および Trident Protect Connector イメージをダウンロードするために使用されます。
... プライベートコンテナレジストリで認証が必要な場合は、以下のいずれかの方法を使用してレジストリの認証情報を設定してください。
+
**** *ノードレベル認証*：各ノードのコンテナランタイムでレジストリ認証情報を設定します。設定が完了すると、すべてのポッドは追加の Helm 設定を必要とせずにイメージをプルできます。
**** *Kubernetes image pull secret*: Kubernetes image pull secret を `trident-protect`名前空間に作成し、Trident Protect のインストール手順の Helm アップグレード手順中にそれを参照します：
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Backup and Recovery に表示されるコマンドラインの手順に従い、必要に応じて Helm ステップ中にイメージプルシークレット情報を追加してください。これらの手順により、Backup and Recovery がクラスターと連携できるようになります。


--
====


. Trident Protect のインストール手順が完了したら、「検出」を選択します。
+
クラスターがインベントリに追加されます。

. 関連付けられている Kubernetes ワークロードで [*表示*] を選択すると、そのワークロードのアプリケーション、クラスター、および名前空間のリストが表示されます。




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== NetApp Backup and Recoveryダッシュボードに進みます

NetApp Backup and Recoveryダッシュボードを表示するには、次の手順に従います。

. NetApp Consoleメニューから、*保護* > *バックアップとリカバリ* を選択します。
. Kubernetesワークロードタイルを選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。
+
link:br-use-dashboard.html["ダッシュボードに表示される内容を学ぶ"]。


