---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery、ワークロードを保護するために、まずワークロードを検出する必要があります。 
---
= NetApp Backup and RecoveryでOracle Databaseワークロードを検出
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracleデータベースを検出すると、NetApp Backup and Recoveryでバックアップとスナップショットを作成およびリストアして保護できるようになります。

*必要なコンソール ロール* バックアップとリカバリのスーパー管理者。詳細はこちらlink:reference-roles.html["バックアップとリカバリの役割と権限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。



[[add-an-oracle-database-host-and-discover-resources]]
== Oracle Databaseホストを追加してリソースを検出する

Oracle ホスト情報を追加し、 NetApp Backup and Recovery でワークロードを検出できるようにします。各コンソール エージェント内で、ワークロードを検出するシステムを選択します。

.手順
. NetApp Consoleメニューから、*保護 > バックアップとリカバリ* を選択します。
. *ワークロード*の下で、*Oracle*タイルを選択します。
. *リソースの検出*を選択します。
. *ワークロード タイプ* フィールドで *Oracle* を選択します。
. この Oracle Database ホストの資格情報をまだ保存していない場合は、*資格情報の追加*を選択します。
+
.. このホストで使用するコンソール エージェントを選択します。
.. この資格情報の名前を入力します。
.. アカウントのユーザー名とパスワードを入力します。
.. *完了*を選択します。


. *ホスト登録*：新しいOracleデータベースホストを追加します。*Host FQDN or IP address*フィールドに、ホストのFQDNまたはIPアドレスを入力します。クラスタ化されたデータベースの場合は、クラスタ内の任意のノードのFQDNまたはIPを入力できます。次に、クレデンシャル、NetApp Consoleエージェント、およびポート番号を指定します。
. （オプション）非ルート ユーザーの資格情報を選択する場合は、次の手順を実行します：
+
.. 選択した非 root ユーザーを Oracle Database ホストの sudoers ファイルに追加する方法については、*sudoers の構成*を選択してください。
.. ダイアログの指示に従い、完了したらチェックボックスを有効にして、*Done* を選択します。


. *詳細設定*：次の操作を行います。
+
.. 使用するポートとインストールパスを入力しますNetAppプラグイン。このプラグインは、Oracle Database ホストとNetApp Backup and Recovery 間の通信を可能にします。
.. NetApp Backup and Recoveryで各ホストにプラグインを自動的にインストールするか、すべてのホストで自動プラグインインストールをスキップするかを選択します。手動インストール手順については、*手順を表示*を選択してください。
+
[NOTE]
====
Backup and Recovery は、SSH を介して各ホストに接続し、プラグインを自動的にインストールします。以下のいずれかに該当する場合は、*手動インストールを使用する*を有効にしてください：

*** 1つ以上のホストでSSHサービスが実行されていません。
*** どのホストにも既にNetAppプラグインがインストールされている（一部のクラスタメンバーのみにインストールされている場合を含む）。
*** 各ホストにプラグインを手動でインストールすることを希望します。


====
.. データベースホストがクラスタ化されている場合は、*クラスタ内のすべてのホストを追加*オプションを有効にして、クラスタ内のすべてのホストを検出します。
.. プラグインを自動的にインストールする前に、各ホストでインストール前のチェックを実行するかどうかを選択します。チェックが失敗した場合、プラグインの自動インストールが停止します。チェックをバイパスしてインストールするには、*Skip optional preinstall checks*を有効にします（手動インストールを選択した場合は自動的に有効になります）。


. *Discover*を選択します。
+

TIP: リソースの追加には数分かかる場合があります。進捗状況を確認するには、Inventoryページ下部のステータスダイアログで*Track progress*を選択するか、左側のメニューから*Monitoring*を選択してください。



.結果
Oracle Database ワークロードは、インベントリ ページのワークロード リストに表示されます。



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== NetApp Backup and Recoveryダッシュボードに進みます

. NetApp Consoleメニューから、*保護* > *バックアップとリカバリ* を選択します。
. ワークロード タイル (Microsoft SQL Server など) を選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。

