---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: NetApp Backup and Recovery のライセンスを取得するには、クラウド プロバイダから従量課金制または年間マーケットプレイスサブスクリプションを購入するか、NetApp からお客様所有のライセンスを購入してください。 
---
= NetApp Backup and Recoveryのライセンスを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console または NetApp Console のローカル展開において、マーケットプレイスのサブスクリプションまたは NetApp のBYOL（Bring Your Own License）を使用して、NetApp Backup and Recovery のライセンスを設定します。サービスの有効化、バックアップの作成、および本番システムへのデータ復元には、有効なライセンスが必要です。

ライセンスの仕組みに関するいくつかの注意点：

* ONTAP ボリュームワークロードを使用する場合、ライセンスなしでボリュームを検出および復元できます。ただし、ボリュームを保護（バックアップ）する必要がある場合は、ライセンスを購入する必要があります。
* バックアップとリカバリを NetApp Console のローカル展開で使用している場合は、BYOL（Bring Your Own License）ライセンスのみ購入できます。
* NetApp Backup and Recovery のBring Your Own License (BYOL) は、 NetApp Console組織またはアカウントに関連付けられているすべてのシステムで使用できるフローティング ライセンスです。したがって、既存の BYOL ライセンスから十分なバックアップ容量を利用できる場合は、別の BYOL ライセンスを購入する必要はありません。
* BYOLライセンスをNetApp Consoleと併用している場合は、PAYGOサブスクリプションにも加入することをお勧めします。BYOLライセンスで許可されている以上のデータをバックアップした場合、またはライセンスの有効期限が切れた場合、バックアップは従量課金制（PAYGO）サブスクリプションを通じて継続されます。サービスの中断はありません。
* オンプレミス の ONTAP データを StorageGRID にバックアップする場合は BYOL ライセンスが必要ですが、クラウド プロバイダのストレージ スペースにかかるコストはありません。


link:concept-backup-to-cloud.html["NetApp Backup and Recoveryの使用に関連するコストについて詳しく説明します。"]



[[licensing-options-for-netapp-backup-and-recovery]]
== NetApp Backup and Recovery のライセンスオプション

NetApp Backup and Recovery のライセンスオプションは3つあります：

* 直接ライセンス（bring-your-own-license（BYOL）とも呼ばれる）を NetApp から購入してください。このオプションは、NetApp Console およびコンソールのローカル展開の両方に適用されます。
* ハイパースケーラーのマーケットプレイスから年間契約を購入します。このオプションはNetApp Consoleにのみ適用されます。
* ハイパースケーラーのマーケットプレイスから従量課金制（PAYGO）ライセンスを契約します。このオプションはNetApp Consoleにのみ適用されます。




[[30-day-free-trial]]
=== 30日間無料トライアル

30日間のNetApp Backup and Recoveryの無料トライアルは、ONTAPボリュームワークロードを除く、ライセンスのないすべてのワークロードでご利用いただけます。ワークロードの使用を開始する際に、そのリソースを検出する前にトライアルを開始できます。トライアルを開始すると、そのステータスと使用容量がNetApp Backup and Recoveryのホームページの*無料トライアル*の下に表示されます。



==== 無料トライアルを終了する

NetApp Backup and Recoveryにログインしたときに表示されるホームページから、ワークロードの無料トライアルをいつでも終了できます。無料トライアル終了後もNetApp Backup and Recoveryの使用を継続する場合は、NetApp Consoleインターフェイスの「Licenses and subscriptions」セクションで有料サブスクリプションを設定する必要があります。NetApp Backup and Recoveryの使用を継続しない場合は、有料プランを契約することなく無料トライアルを終了できます。トライアルが終了する前にlink:prev-ontap-backup-manage.html["NetApp Backup and Recoveryをシステムから登録解除する"]すれば、課金されることはありません。

.手順
. NetApp Backup and Recovery のホームページで、*無料トライアル* の下にある終了したい無料トライアルを選択してください。
. *無料トライアルを終了*を選択します。
. ボックスに「*トライアル終了*」と入力します。
. 確認するには「トライアルを終了する」を選択してください。




[[use-a-byol-license]]
=== BYOLライセンスを使用する

NetAppの Bring-Your-Own ライセンスには、1 年、2 年、または 3 年の契約期間があります。保護するデータに対してのみ料金を支払います。料金は、バックアップ対象のソースONTAPボリュームの論理使用容量（効率性考慮前）に基づいて計算されます。この容量は、フロントエンド テラバイト (FETB) とも呼ばれます。

BYOL NetApp Backup and Recoveryライセンスはフローティング ライセンスであり、 NetApp Console組織またはアカウントに関連付けられているすべてのシステム間で合計容量が共有されます。  ONTAPシステムの場合、CLIコマンドを実行することで、必要な容量の大まかな見積もりを取得できます。 `volume show -fields logical-used-by-afs`バックアップする予定のボリュームに対して。

NetApp Backup and RecoveryのBYOLライセンスをお持ちでない場合は、Consoleの右下にあるチャット アイコンを選択して購入してください。

オプションとして、使用しないCloud Volumes ONTAPの未割り当てのノードベースのライセンスがある場合は、同じドル相当額と同じ有効期限を持つNetApp Backup and Recoveryライセンスに変換できます。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["詳細はこちら"^] 。

NetApp Console または NetApp Console のローカル展開を使用して、BYOL ライセンスを管理します。コンソールから、新しいライセンスの追加、既存のライセンスの更新、およびライセンスの状態の確認を行うことができます。

https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html["ライセンスの追加について学ぶ"^]。



[[use-a-marketplace-license-applies-to-netapp-console-only]]
=== マーケットプレイスライセンスを使用する（NetApp Console のみに適用）

年間契約を購入して、 NetApp Backup and Recoveryを毎年支払います。期間は 1 年、2 年、または 3 年からお選びいただけます。

マーケットプレイスから年間契約を結んでいる場合、NetApp Backup and Recovery の利用料金は、当該契約に基づいて課金されます。

AWSを使用する場合、2つの年間契約から選択できます。 https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWSマーケットプレイスページ"^] Cloud Volumes ONTAPおよびオンプレミスのONTAPシステムの場合:

* Cloud Volumes ONTAPデータとオンプレミスのONTAPデータをバックアップできる「クラウド バックアップ」プラン。
+
このオプションを使用する場合は、マーケットプレイスページからサブスクリプションを設定し、 https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["サブスクリプションをAWS認証情報に関連付ける"^] 。コンソールで AWS 認証情報に割り当てることができるアクティブなサブスクリプションは 1 つだけであるため、この年間契約サブスクリプションを使用してCloud Volumes ONTAPシステムの料金も支払う必要があることに注意してください。

* Cloud Volumes ONTAPとNetApp Backup and Recovery をバンドルできる「CVO Professional」プラン。これには、ライセンスを使用したCloud Volumes ONTAPシステムの無制限のバックアップが含まれます (バックアップ容量はライセンス容量にカウントされません)。このオプションでは、オンプレミスのONTAPデータをバックアップすることはできません。
+
参照 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAPライセンスのトピック"^]このライセンス オプションの詳細については、こちらをご覧ください。

+
このオプションを使用する場合は、 Cloud Volumes ONTAPシステムを作成するときに年間契約を設定でき、コンソールで AWS Marketplace へのサブスクライブを求めるプロンプトが表示されます。



Azure を使用する場合、Cloud Volumes ONTAP およびオンプレミス ONTAP システム向けに、 https://marketplace.microsoft.com/en-us/product/netapp.netapp-bluexp["Azure Marketplace ページ"^]から 2 つの年間契約を利用できます：

* Cloud Volumes ONTAPデータとオンプレミスのONTAPデータをバックアップできる「クラウド バックアップ」プラン。
+
このオプションを使用する場合は、マーケットプレイスページからサブスクリプションを設定し、 https://docs.netapp.com/us-en/console-setup-admin/task-adding-azure-accounts.html#subscribe["サブスクリプションをAzure資格情報に関連付ける"^] 。コンソールで Azure 資格情報に割り当てることができるアクティブなサブスクリプションは 1 つだけであるため、この年間契約サブスクリプションを使用してCloud Volumes ONTAPシステムの料金も支払う必要があることに注意してください。

* Cloud Volumes ONTAPとNetApp Backup and Recovery をバンドルできる「CVO Professional」プラン。これには、ライセンスを使用したCloud Volumes ONTAPシステムの無制限のバックアップが含まれます (バックアップ容量はライセンス容量にカウントされません)。このオプションでは、オンプレミスのONTAPデータをバックアップすることはできません。
+
参照 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAPライセンスのトピック"^]このライセンス オプションの詳細については、こちらをご覧ください。

+
このオプションを使用する場合は、 Cloud Volumes ONTAPシステムを作成するときに年間契約を設定でき、コンソールで Azure Marketplace へのサブスクライブを求めるプロンプトが表示されます。



GCP を使用する場合は、 NetApp の営業担当者に連絡して年間契約を購入してください。この契約は、Google Cloud Marketplace でプライベート オファーとして入手できます。

NetApp がプライベート オファーを共有した後、 NetApp Backup and Recovery のアクティベーション中に Google Cloud Marketplace からサブスクライブするときに年間プランを選択できます。



[[use-a-netapp-backup-and-recovery-paygo-subscription-applies-to-netapp-console-only]]
=== NetApp Backup and Recovery の従量課金制サブスクリプションを使用する（NetApp Console のみに適用）

従量課金制の場合、オブジェクトストレージのコストとNetAppバックアップライセンスのコストを、単一のサブスクリプションで時間単位にクラウド プロバイダへお支払いいただきます。無料トライアルをご利用の場合やライセンス持ち込み（BYOL）の場合でも、Marketplace で *NetApp Intelligent Services* にサブスクライブする必要があります。

* サブスクリプションに登録すると、無料トライアル期間終了後もサービスが中断されることがなくなります。試用期間が終了すると、バックアップしたデータの量に応じて時間ごとに料金が発生します。
* BYOL ライセンスで許可されている量よりも多くのデータをバックアップする場合、データのバックアップと復元の操作は従量課金制サブスクリプションを通じて継続されます。たとえば、10 TiB の BYOL ライセンスがある場合、10 TiB を超えるすべての容量は PAYGO サブスクリプションを通じて課金されます。


無料トライアル期間中、または BYOL ライセンスを超過していない場合は、従量課金制サブスクリプションから料金は請求されません。

NetApp Backup and Recoveryにはいくつかの PAYGO プランがあります。

* Cloud Volumes ONTAPデータとオンプレミスのONTAPデータをバックアップできる「クラウド バックアップ」パッケージ。
* Cloud Volumes ONTAPとNetApp Backup and Recovery をバンドルできる「CVO Professional」パッケージ。これには、ライセンスを使用したCloud Volumes ONTAPシステムの無制限のバックアップが含まれます (バックアップ容量はライセンス容量にカウントされません)。このオプションでは、オンプレミスのONTAPデータをバックアップすることはできません。
+
このオプションには Backup and Recovery の従量課金制サブスクリプションが必要ですが、対象となる Cloud Volumes ONTAP システムには料金は発生しません。



https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["容量ベースのライセンスパッケージの詳細"]。

次のリンクを使用して、クラウド プロバイダー マーケットプレイスからNetApp Backup and Recoveryをサブスクライブします。

* AWS: https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["価格の詳細については、 NetApp Intelligent Servicesのマーケットプレイス オファリングをご覧ください。"^] 。
* Azure： https://marketplace.microsoft.com/en-us/product/netapp.cloud-manager?tab=Overview["価格の詳細については、 NetApp Intelligent Servicesのマーケットプレイス オファリングをご覧ください。"^]。
* Google クラウド: https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["価格の詳細については、 NetApp Intelligent Servicesのマーケットプレイス オファリングをご覧ください。"^] 。




[[exceeding-license-capacity]]
== ライセンス容量の超過

ライセンス容量を超過すると、従量課金制が適用されます。従量課金制のサブスクリプションがない場合、新しいバックアップを作成することはできませんが、サービス保証なしで既存のバックアップを復元することは可能です。ライセンスの有効期限が切れる前に更新してください。有効期限切れのライセンスは、新しいバックアップの作成を妨げ、サービスに支障をきたします。



[[what-happens-when-your-license-expires]]
== ライセンスの有効期限が切れるとどうなりますか？

バックアップおよびリカバリーライセンスの有効期限が切れた場合：

* 既存のバックアップポリシーに基づくバックアップと復元は引き続き正常に機能します。
* 新しいバックアップポリシーを作成したり、追加のワークロードやデータストアに保護範囲を拡張したりすることはできません。
* 新しいバックアップおよびリカバリ機能や拡張機能は使用できません。
* NetApp のバックアップおよびリカバリに関するテクニカルサポートは終了いたしました。


ライセンスを更新する理由：

* データベース、仮想マシン、Kubernetesワークロードのアプリケーション整合性バックアップに関するポリシーを含め、バックアップポリシーを作成および変更します。
* 新しいバックアップおよびリカバリ機能と強化機能をご活用ください。
* 引き続きNetAppのテクニカルサポートを受けることができます。

