---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery、サービスを使用するために、まずワークロードを検出する必要があります。 
---
= NetApp Backup and Recoveryで Kubernetes ワークロードを発見
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery、 Kubernetes ワークロードを保護する前に検出する必要があります。

*必要なNetApp Consoleロール* バックアップおよびリカバリのスーパー管理者。詳細はこちらlink:reference-roles.html["バックアップとリカバリの役割と権限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。



== Kubernetes ワークロードを発見する

バックアップとリカバリのインベントリで、環境内の Kubernetes ワークロードを検出します。ワークロードを追加すると、NetApp Backup and Recoveryに Kubernetes クラスターが追加されます。その後、アプリケーションを追加し、クラスター リソースを保護できます。

[NOTE]
====
現在Trident Protectで保護されているクラスタを検出すると、Trident Protectで使用されていたバックアップスケジュールは検出プロセス中に無効になります（Trident Protectのバックアップスケジュールはバックアップおよびリカバリと互換性がありません）。クラスタのアプリケーションを保護するには、link:br-use-policies-create.html["新しい保護ポリシーを作成する"]または、アプリケーションを既存のポリシーに関連付けます。その後、必要に応じてTrident Protectのバックアップスケジュールを削除できます。

====
.手順
. 次のいずれかを実行します。
+
** Kubernetes ワークロードを初めて検出する場合は、 NetApp Backup and Recovery の*ワークロード* で、*Kubernetes* タイルを選択します。
** Kubernetes ワークロードをすでに検出している場合は、 NetApp Backup and Recoveryで *インベントリ* > *ワークロード* を選択し、*リソースの検出* を選択します。


. *Kubernetes* ワークロード タイプを選択します。
. クラスター名を入力し、クラスターで使用するコネクタを選択します。
. 表示されるコマンド ラインの指示に従います。
+
** Trident Protect ネームスペースを作成する
** Kubernetesシークレットを作成する
** Helmリポジトリを追加する
** Trident Protectおよび Trident Protect コネクタのインストールまたはアップグレード
+
これらの手順により、 NetApp Backup and Recovery がクラスターと対話できるようになります。



. 手順を完了したら、[*検出*] を選択します。
+
クラスターがインベントリに追加されます。

. 関連付けられている Kubernetes ワークロードで [*表示*] を選択すると、そのワークロードのアプリケーション、クラスター、および名前空間のリストが表示されます。




== NetApp Backup and Recoveryダッシュボードに進みます

NetApp Backup and Recoveryダッシュボードを表示するには、次の手順に従います。

. NetApp Consoleメニューから、*保護* > *バックアップとリカバリ* を選択します。
. ワークロード タイル (Microsoft SQL Server など) を選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
. データ保護の健全性を確認します。新しく検出され、保護され、バックアップされたワークロードに基づいて、危険にさらされているワークロードまたは保護されているワークロードの数が増加します。
+
link:br-use-dashboard.html["ダッシュボードに表示される内容を学ぶ"]。


