---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Consoleを使用して、 NetApp Backup and Recoveryサービスにログインします。 
---
= NetApp Backup and Recoveryにログイン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleを使用してNetApp Backup and Recoveryにログインします。

NetApp Backup and Recovery は、アイデンティティおよびアクセス管理を使用して、各ユーザーが実行できる操作を制御します。

各ロールが実行できるアクションの詳細については、link:reference-roles.html["NetApp Backup and Recoveryのユーザー ロール"] 。

NetApp Consoleにログインするには、 NetAppサポート サイトの認証情報を使用するか、電子メールとパスワードを使用してNetApp Consoleログインにサインアップすることができます。 https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["ログインについて詳しくはこちら"^] 。

*必要なNetApp Consoleロール* バックアップおよびリカバリのスーパー管理者またはバックアップおよびリカバリの復元管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

コンソール エージェントを追加するには、バックアップとリカバリのスーパー管理者ロールが必要です。

.手順
. ウェブブラウザを開いて、 https://console.netapp.com/["NetApp Console"^] 。
+
NetApp Consoleのログイン ページが表示されます。

. コンソールにログインします。
. コンソールの左側のナビゲーションから、*保護* > *バックアップとリカバリ*を選択します。
+
** バックアップおよびリカバリに初めてログインし、*システム* ページにまだシステムを追加していない場合は、バックアップおよびリカバリに、システムを追加するオプションを含む「新しいNetApp Backup and Recoveryへようこそ」ランディング ページが表示されます。*システム*ページにシステムを追加する方法の詳細については、 https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["NetApp Console標準モードの使用開始"^]。
** 初めて Backup and Recovery にログインし、コンソールにシステムがあるがリソースが検出されていない場合は、[新しいNetApp Backup and Recovery へようこそ] ページが表示され、[リソースの検出] オプションが表示されます。


. まだ行っていない場合は、[*検出と管理*] オプションを選択します。
+
** Microsoft SQL Serverのワークロードについては、以下を参照してください。link:br-start-discover.html["Microsoft SQL Server ワークロードの検出"] 。
** VMwareワークロードについては、link:br-use-vmware-discovery.html["VMware ワークロードを発見"] 。
** KVMワークロードについては、link:br-start-discover-kvm.html["KVMワークロードを発見"] 。
** Oracleデータベースのワークロードについては、link:br-start-discover-oracle.html["Oracle Databaseワークロードを検出"]を参照してください。
** Hyper-Vワークロードについては、以下を参照してください。link:br-start-discover-hyperv.html["Hyper-V ワークロードの検出"] 。
** Kubernetesワークロードについては、以下を参照してください。link:br-start-discover-kubernetes.html["Kubernetes ワークロードを発見する"] 。



