---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: 質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。 
---
= NetApp Backup and Recoveryに関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。



== 導入

* NetApp Backup and Recoveryプレビュー バージョンを使用するにはライセンスが必要ですか?*

次のライセンス タイプを使用できます。

* 30 日間の無料トライアルにサインアップしてください。


* NetApp Backup and Recoveryを有効にするにはどうすればいいですか?* NetApp Backup and Recovery有効化は必要ありません。コンソールの左側のナビゲーションで、バックアップとリカバリのオプションが自動的に有効になります。

開始するには、サインアップするか、 NetApp の営業担当者に連絡してバックアップとリカバリを試す必要があります。その後、コンソール エージェントを使用すると、サービスに適切な機能が含まれるようになります。

NetApp Backup and Recovery の使用を開始するには、最初のランディング ページから「ワークロードの検出を開始する」を選択します。

* NetApp Backup and Recovery は、標準モード、制限モード、プライベート モードで使用できますか?*現在、 NetApp Backup and Recovery は標準モードでのみ利用可能です。今後もご期待ください。

NetAppデータサービス全体にわたるこれらのモードの説明については、 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Consoleの展開モード"^] 。



== アクセス

* NetApp Backup and RecoveryURL とは何ですか?*  URL については、ブラウザで次のように入力します。 https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^] NetApp Consoleにアクセスします。

*アクセス権限はどのように処理されますか?*サービスを開始し、ワークロードを検出できるのは組織管理者のみです (これにはリソースの使用をコミットする必要があるため)。後続のやり取りはどのロールでも実行できます。

*どのデバイスの解像度が最適ですか?*NetApp Backup and Recoveryに推奨されるデバイス解像度は 1920 x 1080 以上です。

*どのブラウザを使用すればよいですか?*どの最新ブラウザでも動作します。



== 他のサービスとのやり取り

* NetApp Backup and Recovery は、 NetApp ONTAPで行われた保護設定を認識しますか?*はい、 NetApp Backup and Recovery はONTAPで設定されたスナップショット スケジュールを検出します。

* NetApp Backup and Recoveryを使用してポリシーを設定した場合、今後の変更は Backup and Recovery でのみ行う必要がありますか?*ポリシーの変更はNetApp Backup and Recoveryから行うことをお勧めします。



== ワークロード

*作業負荷を構成するものは何ですか?*ワークロードは、Preview 2025 バージョンのアプリケーションです。ワークロードには、単一のアプリケーション インスタンスによって使用されるすべてのボリュームが含まれます。たとえば、mssql3.host.com にデプロイされた Microsoft SQL Server DB インスタンスには、データ用に vol1、ログ用に vol2 がそれぞれ存在する場合があります。これらのボリュームが組み合わさって、DB インスタンスの特定のインスタンスのワークロードを構成します。

* NetApp Backup and Recovery はどのようなワークロードをサポートしていますか?*

Preview 2025 バージョンでは、 NetApp Backup and Recovery は次のワークロードを識別できます: Microsoft SQL Server アプリケーション。

*「保護された」ワークロードとは何ですか?*NetApp Backup and Recoveryでは、プライマリ検出ポリシーが有効になっている場合、ワークロードは「保護済み」ステータスを表示します。

*「リスクのある」ワークロードとは何ですか?*ワークロードでプライマリ検出ポリシーが有効になっていない場合、バックアップおよびスナップショット ポリシーが有効になっていても、ワークロードは「危険にさらされている」状態になります。

*新しいワークロードが追加されましたが、まだ表示されません* 環境に新しいワークロードを追加した場合は、検出を再度開始し、保護ポリシーを適用してその新しいリソースを保護します。



== 保護ポリシー

* NetApp Backup and Recovery は、 NetApp ONTAPで行われた保護設定を認識しますか?*

はい、 NetApp Backup and Recovery は、 ONTAPで設定されたスナップショット スケジュールと、検出されたワークロードで ARP と FPolicy が有効になっているかどうかを検出します。ダッシュボードに最初に表示される情報は、他のNetAppソリューションおよび製品から集約されたものです。

* NetApp Backup and Recovery は、 SnapCenterですでに作成されているポリシーを認識しますか?*

はい、 SnapCenterで管理されているワークロードがある場合、それらの製品によって管理されているポリシーはNetApp Backup and Recoveryに取り込まれます。

* SnapCenterから引き継がれたポリシーを変更できますか?*

はい、 NetApp Backup and Recovery内でSnapCenterによって管理されていたポリシーを変更できます。

* ONTAPからのポリシーが存在する場合 (ARP、FPolicy、スナップショットなど、System Manager ですでに有効になっている)、それらのポリシーはNetApp Backup and Recoveryで変更されますか? *

いいえ。NetApp NetApp Backup and Recovery は、 ONTAPの既存の検出ポリシー (ARP、FPolicy 設定) を変更しません。

* NetApp Backup and Recoveryにサインアップした後、 SnapCenterに新しいポリシーを追加するとどうなりますか?*

NetApp Backup and Recovery は、 SnapCenterで作成された新しいポリシーを認識します。

* ONTAPからポリシーを変更できますか?*

はい、 NetApp Backup and RecoveryのONTAPからポリシーを変更できます。 NetApp Backup and Recoveryで新しいポリシーを作成し、ワークロードに適用することもできます。このアクションにより、既存のONTAPポリシーがNetApp Backup and Recoveryで作成されたポリシーに置き換えられます。
