---
sidebar: sidebar 
permalink: br-use-hyperv-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: オンプレミスのONTAPシステムからプライマリ ストレージおよびセカンダリ ストレージまで、Hyper-V 仮想マシンを保護して、データが確実に保護されるようにすることができます。 
---
= NetApp Backup and RecoveryによるHyper-Vワークロードの保護
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery を使用して、スタンドアロンの Hyper-V VM、フェールオーバークラスタインスタンス、および CIFS 共有上でホストされている SCVMM でプロビジョニングされた VM をバックアップおよびリストアします。

Hyper-V ワークロードを Amazon S3 または StorageGRID にバックアップし、オンプレミスの Hyper-V ホストにリストアできます。

NetApp Backup and Recovery を使用して、3-2-1 の保護戦略を実装します。これは、ソースデータの 3 つのコピーを 2 つの異なるストレージシステムに、1 つのコピーをクラウドに保存するものです。3-2-1 方式の利点は以下のとおりです：

* 複数のデータ コピーにより、内部および外部のサイバー セキュリティの脅威から保護されます。
* 複数のメディア タイプにより、1 つのメディア タイプに物理的または論理的な障害が発生した場合でも、フェイルオーバーの実行可能性が確保されます。
* オンサイトコピーはデータをすばやく復元するのに役立ち、オンサイトコピーが侵害された場合はオフサイトコピーを使用できます。


Hyper-V ホストを追加してリソースを検出すると、NetApp Backup and Recovery は NetApp Hyper-V プラグインと NetApp SnapCenter Windows FileSystem プラグインを各 Hyper-V ホストにインストールし、仮想マシンの管理と保護を支援します。

NetApp Backup and Recoveryを使用すると、Hyper-V ワークロードに関連する次のタスクを実行できます。

* link:br-start-discover-hyperv.html["Hyper-V ワークロードの検出"]
* link:br-use-hyperv-protection-groups.html["Hyper-V ワークロードの保護グループの作成と管理"]
* link:br-use-hyperv-backup.html["Hyper-V ワークロードのバックアップ"]
* link:br-use-hyperv-restore.html["Hyper-V ワークロードを復元する"]

