---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: NetApp Backup and Recoveryでは、バックアップの数、成功したバックアップの数、失敗したバックアップの数など、バックアップのステータスを表示するレポートを作成します。バックアップの種類、バックアップに使用されたストレージ システム、バックアップの時間など、各バックアップの詳細を表示することもできます。 
---
= NetApp Backup and Recovery で Microsoft SQL Server 保護レポートを作成する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Backup and RecoveryでMicrosoft SQL Serverワークロードのレポートを作成し、成功および失敗したバックアップの数、バックアップ タイプ、ストレージ システム、タイムスタンプなどのバックアップ ステータスと詳細を確認します。



[[create-a-protection-report]]
== 保護レポートを作成する

*必須 NetApp コンソールロール* ストレージビューアー、バックアップとリカバリのスーパー管理者、バックアップとリカバリのバックアップ管理者、バックアップとリカバリのリストア管理者、バックアップとリカバリのクローン管理者。Cloud Volumes ONTAP クラスターに保存されているデータを保護する場合は、Cloud Volumes ONTAP 管理者ロールも必要です。link:reference-roles.html["バックアップとリカバリの役割と権限"] について学ぶ。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]。

.手順
. NetApp Backup and Recovery メニューから、「レポート」を選択します。
. *レポートの作成*を選択します。
. レポート範囲の詳細を入力します:
+
** *レポート名*: レポートの一意の名前を入力します。
** *レポート タイプ*: アカウント別またはワークロード (Microsoft SQL Server) 別にレポートを作成するかどうかを選択します。
** *ホストを選択*: ワークロードで選択した場合は、レポートを生成するホストを選択します。
** *コンテンツの選択*: レポートにすべてのバックアップの概要を含めるか、各バックアップの詳細を含めるかを選択します。  （「アカウント別」を選択した場合）


. レポート対象期間を入力してください：レポートに含めるデータ期間を、直近1日、直近7日間、直近30日間、直近四半期、または直近1年間から選択してください。
. レポートの配信詳細を入力してください：レポートをメールで送信する場合は、「レポートをメールで送信」を選択してください。レポートの送信先となるメールアドレスを入力してください。
+
設定ページでメール通知を設定してください。メール通知の設定方法の詳細については、link:br-start-configure.html["設定を構成する"]を参照してください。


