---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: NetApp Backup and Recoveryを使用して Hyper-V ワークロードを保護します。 
---
= NetApp Backup and Recoveryを使用して Hyper-V ワークロードを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ローカル スナップショット、セカンダリ ストレージ上のレプリケート バックアップ、またはオブジェクト ストレージのバックアップから Hyper-V ワークロードを復元するには、NetApp Backup and Recovery を使用します。

.これらの場所から復元
以下の場所からワークロードを復元できます：

* プライマリロケーション（ローカルスナップショット）からの復元
* セカンダリストレージ上の複製されたリソースから復元する
* オブジェクトストレージバックアップからの復元


.これらのポイントに復元する
データを復元できる先は以下のとおりです：

* 元の場所に復元します（プライマリストレージ、セカンダリストレージ、オブジェクトストレージから）
* 別の場所に復元する（プライマリストレージ、セカンダリストレージ、オブジェクトストレージから）


.オブジェクトストレージからの復元に関する考慮事項
オブジェクトストレージでバックアップファイルを選択し、バックアップ ポリシーで DataLock とランサムウェア対策を有効にしたことによってそのバックアップに対してランサムウェア対策が有効になっている場合、データを復元する前に追加の整合性チェックを実行するように求められます。スキャンを実行することをお勧めします。


TIP: バックアップ ファイルの内容にアクセスするには、クラウド プロバイダーから追加の送信コストが発生します。



[[how-restoring-workloads-works]]
== ワークロードの復元の仕組み

ワークロードを復元すると、次のことが発生します：

* ローカル バックアップ ファイルからワークロードを復元すると、 NetApp Backup and Recovery はバックアップのデータを使用して新しいリソースを作成します。
* 複製されたワークロードから復元する場合、ワークロードを元のシステムまたはオンプレミスのONTAPシステムに復元できます。


復元ページからは、リソースの正確な名前、場所、または最後に正常にバックアップされた日付を覚えていなくても、リソースを復元できます。フィルターを使用してスナップショットを検索できます。



[[restore-hyper-v-workloads]]
== Hyper-V ワークロードを復元する

「復元」メニューを使用して、Hyper-Vワークロードを復元します。スナップショットは、名前で検索することも、フィルターを使用して検索することもできます。

*必須NetApp Console ロール* バックアップおよびリカバリのスーパー管理者、またはバックアップおよびリカバリのリストア管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]

.手順
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*Hyper-V* を選択します。
. 復元するリソースの名前を入力するか、VM名、VMホスト、またはリソースが配置されているストレージプールでフィルタリングしてください。
+
検索条件に一致するスナップショットのリストが表示されます。

. 復元したいスナップショットの*復元*ボタンを選択します。
+
可能な復元ポイントのリストが表示されます。

. 使用する復元ポイントを選択します。
. スナップショットのソースの場所を選択します。
. 続行するには、[次へ] を選択します。
. 復元先と設定を選択します。
+
[discrete]
===== 目的地の選択

+
[role="tabbed-block"]
====
.元の場所へのリストア
--
.. * Original location * ペインを選択します。元の場所に復元すると、* Destination settings * セクションを展開することで保存先設定を表示できますが、変更することはできません。
.. *復元後のオプション* セクションで、次のオプションを検討してください。
+
*** *仮想マシンを起動*: このオプションを有効にすると、復元後に新しい仮想マシンを起動できます。




--
.別の場所へのリストア
--
.. *代替の場所* ペインを選択します。
.. 「宛先設定」セクションで、以下の情報を入力してください：
+
*** *Hyper-V FQDN または IP アドレス*: 宛先 Hyper-V ホストの完全修飾ドメイン名または IP アドレスを入力します。
*** *ネットワーク*: スナップショットを復元する宛先ネットワークを選択します。
*** *仮想マシン名*: 復元する仮想マシンの名前を入力します。
*** *宛先場所*: 復元されたデータを保存する宛先フォルダまたは CIFS 共有を入力します。


.. 「宛先ストレージ」セクション（オブジェクトストレージから復元する場合のみ表示されます）：
+
*** *デフォルトの保存場所を変更する*：このオプションを有効にすると、ソースの保存場所にアクセスできない場合や、容量がいっぱいの場合に、オブジェクトストアのバックアップを別の場所に復元できます。別のクラスター、ストレージVM、またはアグリゲートを選択してください。


.. 「復元前のオプション」セクションでは、以下のオプションを検討してください：
+
*** *クイック復元*: このオプションを有効にすると、復元された VM をすぐに使用できるようになります。ボリューム全体ではなく、VM の実行に必要なファイルのみがオブジェクト ストアから復元されます。


.. 「復元後のオプション」セクションでは、以下のオプションを考慮してください。
+
*** *仮想マシンを起動*: このオプションを有効にすると、復元後に新しい仮想マシンを起動できます。




--
====
. *復元*を選択します。

