---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: NetApp Backup and Recoveryを使用して Hyper-V ワークロードを保護します。 
---
= NetApp Backup and Recoveryを使用して Hyper-V ワークロードを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recoveryを使用して、スナップショット、セカンダリ ストレージに複製されたワークロード バックアップ、またはオブジェクト ストレージに保存されたバックアップから Hyper-V ワークロードを復元します。

.これらの場所から復元
異なる開始場所からワークロードを復元できます。

* プライマリロケーション（ローカルスナップショット）からの復元
* セカンダリストレージ上の複製されたリソースから復元する
* オブジェクトストレージバックアップからの復元


.これらのポイントに復元する
以下のポイントまでデータを復元できます:

* 元の場所に復元する
* 別の場所に復元する


.オブジェクトストレージからの復元に関する考慮事項
オブジェクト ストレージでバックアップ ファイルを選択し、そのバックアップに対してランサムウェア保護がアクティブになっている場合（バックアップ ポリシーで Datalock とランサムウェア保護を有効にした場合）、データのリストア前にバックアップ ファイルに対して追加の整合性チェックを実行するように求められます。スキャンを実行することを推奨します。


TIP: バックアップ ファイルの内容にアクセスするには、クラウド プロバイダーから追加の送信コストが発生します。



== ワークロードの復元の仕組み

ワークロードを復元すると、次のことが起こります。

* ローカル バックアップ ファイルからワークロードを復元すると、 NetApp Backup and Recovery はバックアップのデータを使用して新しいリソースを作成します。
* 複製されたワークロードから復元する場合、ワークロードを元のシステムまたはオンプレミスのONTAPシステムに復元できます。


「復元」ページからは、リソースの正確な名前、保存場所、最後に正常に動作していた日付を覚えていなくても、リソースを復元できます。フィルターを使用してスナップショットを検索できます。



== Hyper-V ワークロードを復元する

「復元」メニューを使用して、Hyper-Vワークロードを復元します。スナップショットは、名前で検索するか、フィルタを使用して検索できます。

*必要なコンソール ロール* バックアップおよびリカバリのスーパー管理者またはバックアップおよびリカバリの復元管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

.手順
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*Hyper-V* を選択します。
. 復元するリソースの名前を入力するか、復元するリソースが配置されている VM 名、VM ホスト、またはストレージ プールでフィルターします。
+
検索条件に一致するスナップショットのリストが表示されます。

. 復元したいスナップショットの*復元*ボタンを選択します。
+
可能な復元ポイントのリストが表示されます。

. 使用する復元ポイントを選択します。
. スナップショットのソースの場所を選択します。
. 続行するには、[次へ] を選択します。
. 復元先と設定を選択します。
+
[discrete]
===== 目的地の選択

+
[role="tabbed-block"]
====
.元の場所へのリストア
--
.. * Original location * ペインを選択します。元の場所に復元すると、* Destination settings * セクションを展開することで保存先設定を表示できますが、変更することはできません。
.. *復元後のオプション* セクションで、次のオプションを検討してください。
+
*** *仮想マシンを起動*: このオプションを有効にすると、復元後に新しい仮想マシンを起動できます。




--
.別の場所へのリストア
--
.. *代替の場所* ペインを選択します。
.. *宛先設定*: セクションで、次の情報を入力します。
+
*** *Hyper-V FQDN または IP アドレス*: 宛先 Hyper-V ホストの完全修飾ドメイン名または IP アドレスを入力します。
*** *ネットワーク*: スナップショットを復元する宛先ネットワークを選択します。
*** *仮想マシン名*: 復元する仮想マシンの名前を入力します。
*** *宛先場所*: 復元されたデータを保存する宛先フォルダまたは CIFS 共有を入力します。


.. *復元前オプション* セクションで、次のオプションを検討してください。
+
*** *クイック復元*: このオプションを有効にすると、復元された VM をすぐに使用できるようになります。ボリューム全体ではなく、VM の実行に必要なファイルのみがオブジェクト ストアから復元されます。


.. *復元後のオプション*セクションで、次のオプションを検討してください。
+
*** *仮想マシンを起動*: このオプションを有効にすると、復元後に新しい仮想マシンを起動できます。




--
====
. *復元*を選択します。

