---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: オンプレミスのONTAPシステムから Amazon Web Services、Microsoft Azure、Google Cloud Platform、 StorageGRIDに至るまで、Oracle 仮想マシンを保護して、データを確実に保護できます。 
---
= Oracle Databaseワークロードの保護の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recoveryを使用してOracleデータベースとログを保護します。高速でスペース効率に優れた「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態およびデータベース整合性のあるバックアップとリストアを実現します。Oracle DatabaseワークロードをAWS S3、NetApp StorageGRID、Azure Blob Storage、またはONTAP S3にバックアップします。バックアップをオンプレミスのOracleホストにリストアします。

NetApp Backup and Recoveryを使用して 3-2-1 保護戦略を実装します。この戦略では、ソース データのコピーを 2 つの異なるストレージ システムに 3 つ、クラウドに 1 つ保存します。3-2-1 アプローチの利点は次のとおりです。

* 複数のデータ コピーにより、内部および外部のサイバー セキュリティの脅威から保護されます。
* 異なるタイプのメディアを使用すると、1 つのタイプに障害が発生した場合でも回復しやすくなります。
* オンサイト コピーから迅速に復元し、オンサイト コピーが侵害された場合はオフサイト コピーを使用できます。



NOTE: NetApp Backup and Recovery UIのバージョンを切り替えるには、link:br-start-switch-ui.html["以前のNetApp Backup and RecoveryUIに切り替える"] 。

NetApp Backup and Recoveryを使用して、Oracleデータベースワークロードに関連する次のタスクを実行できます：

* link:br-start-discover-oracle.html["Oracle Databaseワークロードを検出"]
* link:br-use-oracle-protection-groups.html["Oracle Database ワークロードの保護グループの作成と管理"]
* link:br-use-oracle-backup.html["Oracle Databaseワークロードのバックアップ"]
* link:br-use-oracle-restore.html["Oracle Database ワークロードのリストア"]

