---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery を使用すると、ワークロード ホスト情報、データベース情報、インスタンス情報を管理できます。インベントリの保護設定を表示、編集、削除できます。 
---
= Kubernetes アプリケーションの追加と保護
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery を使用すると、kubeconfig ファイルを生成してアップロードしなくても、Kubernetes クラスターを簡単に検出できます。  NetApp Consoleのユーザー インターフェイスからコピーした簡単なコマンドを使用して、Kubernetes クラスターを接続し、必要なソフトウェアをインストールできます。

.必要なNetApp Consoleロール
組織管理者またはSnapCenter管理者。link:reference-roles.html["NetApp Backup and Recoveryのアクセス ロールについて学習します"] 。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。



== 新しいKubernetesアプリケーションを追加して保護する

Kubernetes アプリケーションを保護するための最初のステップは、NetApp Backup and Recovery内にアプリケーションを作成することです。アプリケーションを作成すると、Kubernetes クラスター上で実行中のアプリケーションがコンソールに認識されます。

.開始する前に
Kubernetesアプリケーションを追加して保護する前に、link:br-start-discover.html["Kubernetesワークロードを発見する"] 。

.手順
. NetApp Backup and Recoveryで、*Inventory* を選択します。
. Kubernetes インスタンスを選択し、[表示] を選択して、そのインスタンスに関連付けられているリソースを表示します。
. *アプリケーション*タブを選択します。
. *アプリケーションの作成*を選択します。
. アプリケーションの名前を入力します。
. 必要に応じて、次のいずれかのフィールドを選択して、保護するリソースを検索します。
+
** 関連クラスター
** 関連する名前空間
** リソースの種類
** ラベルセレクター


. 必要に応じて、「*クラスタースコープリソース*」を選択して、クラスターレベルでスコープ指定されたリソースを選択します。これらのリソースを含めると、アプリケーションの作成時にアプリケーションに追加されます。
. 必要に応じて、「*検索*」を選択し、検索条件に基づいてリソースを検索します。
+

NOTE: コンソールには検索パラメータや結果は保存されません。パラメータは、選択した Kubernetes クラスターでアプリケーションに含めることができるリソースを検索するために使用されます。

. コンソールには、検索条件に一致するリソースのリストが表示されます。
. 保護するリソースがリストに含まれている場合は、[次へ] を選択します。
. 必要に応じて、「*ポリシー*」領域で、アプリケーションを保護するための既存の保護ポリシーを選択するか、新しいポリシーを作成します。ポリシーを選択しない場合、アプリケーションは保護ポリシーなしで作成されます。あなたはできるlink:br-use-policies-create.html#create-a-policy["保護ポリシーを追加する"]後で。
. *プレスクリプトとポストスクリプト*領域で、バックアップ操作の前または後に実行するプレスクリプトまたはポストスクリプトの実行フックを有効にして構成します。プレスクリプトまたはポストスクリプトを有効にするには、少なくとも1つ作成しておく必要があります。link:br-use-manage-execution-hook-templates.html["実行フックテンプレート"] 。
. *作成*を選択します。


.結果
アプリケーションが作成され、Kubernetes インベントリの *アプリケーション* タブのアプリケーション リストに表示されます。  NetApp Consoleは設定に基づいてアプリケーションの保護を有効にし、バックアップとリカバリの *監視* 領域で進行状況を監視できます。



== 既存のKubernetesアプリケーションを保護する

すでに追加した Kubernetes アプリケーションで保護ポリシーを有効にします。

.手順
. NetApp Backup and Recoveryで、*Inventory* を選択します。
. Kubernetes インスタンスを選択し、[表示] を選択して、そのインスタンスに関連付けられているリソースを表示します。
. *アプリケーション*タブを選択します。
. アプリケーションのリストで、保護するアプリケーションを選択し、関連する [アクション] メニューを選択します。
. *保護*を選択します。
. *ポリシー* 領域で、アプリケーションを保護するための既存の保護ポリシーを選択するか、新しいポリシーを作成します。参照link:br-use-policies-create.html#create-a-policy["ポリシーを作成します。"]保護ポリシーの作成の詳細については、こちらをご覧ください。
. *プレスクリプトとポストスクリプト*領域で、バックアップ操作の前または後に実行するプレスクリプトまたはポストスクリプトの実行フックを有効にして構成します。実行フックのタイプ、使用するテンプレート、引数、ラベルセレクターを構成できます。
. *完了*を選択します。


.結果
コンソールは設定に基づいてアプリケーションの保護を有効にし、バックアップとリカバリの *監視* 領域で進行状況を監視できます。アプリケーションの保護を有効にするとすぐに、コンソールはアプリケーションの完全バックアップを作成します。その後の増分バックアップは、アプリケーションに関連付けられた保護ポリシーで定義されたスケジュールに基づいて作成されます。



== Kubernetesアプリケーションを今すぐバックアップ

将来のバックアップとスナップショットのベースラインを確立するため、または最新のデータが保護されていることを確認するために、Kubernetes アプリケーションのバックアップを手動で作成します。

.手順
. NetApp Backup and Recoveryで、*Inventory* を選択します。
. Kubernetes インスタンスを選択し、[表示] を選択して、そのインスタンスに関連付けられているリソースを表示します。
. *アプリケーション*タブを選択します。
. アプリケーションのリストで、バックアップするアプリケーションを選択し、関連する [アクション] メニューを選択します。
. *今すぐバックアップ*を選択します。
. 正しいアプリケーション名が選択されていることを確認してください。
. *バックアップ*を選択します。


.結果
コンソールはアプリケーションのバックアップを作成し、バックアップとリカバリの *監視* 領域に進行状況を表示します。バックアップは、アプリケーションに関連付けられた保護ポリシーに基づいて作成されます。
