---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: ワークロードの健全性を監視することで、ワークロード保護に関する問題を認識し、解決するための手順を実行できるようになります。バックアップとリストアのステータスを表示し、 NetApp Backup and Recoveryダッシュボードに表示されるアラートに応答します。保護の概要、復元の概要、システムの概要などを確認できます。 
---
= バックアップとリカバリのダッシュボードで保護の状態を確認する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ワークロードの状態を監視して、保護上の問題を特定し、アラートに対応します。バックアップと復元のステータスを表示し、NetApp Backup and Recovery ダッシュボードでシステム、保護、ジョブ、復元の概要を確認します。

*必須 NetApp Console ロール* Backup and Recovery スーパー管理者、Backup and Recovery バックアップ管理者、Backup and Recovery リストア管理者、Backup and Recovery クローン管理者、または Backup and Recovery バックアップビューアロール。Cloud Volumes ONTAP クラスターに保存されているデータを保護している場合は、Cloud Volumes ONTAP 管理者ロールも必要です。詳細については、link:reference-roles.html["バックアップとリカバリの役割と権限"]を参照してください。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]

.手順
. NetApp Console メニューから、*Protection* > *Backup and Recovery* を選択します。
. ワークロード タイル (Microsoft SQL Server など) を選択します。
. 「バックアップとリカバリ」メニューから、「ダッシュボード」を選択します。
+
次の種類の情報を確認できます。

+
** 検出されたホストまたはVMの数
** 検出されたKubernetesクラスターの数
** オブジェクトストレージ上のバックアップ対象の数
** vCenterの数
** ONTAPのストレージクラスタの数






[[view-the-protection-summary]]
== 保護の概要を表示する

保護の概要で次の情報を確認します。

* 保護されているデータベース、VM、データストアと保護されていないデータベース、VM、データストアの合計数。
+

TIP: 保護されたデータベースとは、バックアップ ポリシーが割り当てられたデータベースです。保護されていないデータベースとは、バックアップ ポリシーが割り当てられていないデータベースです。

* 成功したバックアップ、警告のあったバックアップ、失敗したバックアップの数。
* バックアップ サービスによって検出された合計容量と、保護されている容量と保護されていない容量。  「*i*」アイコンにマウスを合わせると詳細が表示されます。




[[view-the-job-summary]]
== 求人概要を見る

ジョブ概要で、完了済み、実行中、または失敗したジョブの総数を確認してください。

.手順
. 各ジョブ分布について、フィルターを変更して、失敗したジョブ、実行中のジョブ、完了したジョブの概要を日数に基づいて表示します。たとえば、過去30日間、過去7日間、過去24時間、または過去1年間などです。
. *ジョブ監視の表示*を選択すると、失敗したジョブ、実行中のジョブ、完了したジョブの詳細が表示されます。




[[view-the-restore-summary]]
== 復元の概要を表示する

復元概要に記載されている以下の情報を確認してください。

* 実行された復元ジョブの合計数
* 回復した容量の合計
* ローカル、セカンダリ、オブジェクト ストレージで実行された復元ジョブの数。グラフの上にマウスを移動すると詳細が表示されます。

