---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery を使用すると、保護ポリシーで保護したアプリケーションを復元できます。 
---
= Kubernetesアプリケーションを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery を使用すると、保護ポリシーで保護したアプリケーションを復元できます。アプリケーションを復元するには、少なくとも 1 つの復元ポイントが必要です。復元ポイントは、ローカル スナップショットまたはオブジェクト ストアへのバックアップ（あるいはその両方）で構成されます。アプリケーションは、ローカル アーカイブ、セカンダリ アーカイブ、またはオブジェクト ストア アーカイブを使用して復元できます。

.必要なNetApp Consoleロール
組織管理者またはSnapCenter管理者。link:reference-roles.html["NetApp Backup and Recoveryのアクセス ロールについて学習します"] 。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

.手順
. NetApp Backup and Recoveryで、*Inventory* を選択します。
. Kubernetes インスタンスを選択し、[表示] を選択して、そのインスタンスに関連付けられているリソースを表示します。
. *アプリケーション*タブを選択します。
. アプリケーションのリストで、復元するアプリケーションを選択し、関連する [アクション] メニューを選択します。
. *表示と復元*を選択します。
+
復元ポイントのリストが表示されます。

. 使用する復元ポイントの「アクション」メニューを開き、「復元」を選択します。


[discrete]
===== 一般設定

. 復元元のソース (ローカルまたはオブジェクト ストア) を選択します。
. *クラスター* リストから宛先クラスターを選択します。
. 復元先の名前空間を選択します。
+
元の名前空間に復元することも、新しい名前空間に復元することもできます。

. *次へ*を選択します。


[discrete]
===== リソースの選択

. アプリケーションに関連付けられているすべてのリソースを復元するか、フィルターを使用して復元する特定のリソースを選択するかを選択します。


[role="tabbed-block"]
====
.すべてのリソースを復元する
--
. *すべてのリソースを復元*を選択します。
. *次へ*を選択します。


--
.特定のリソースを復元する
--
. *選択的リソース*を選択します。
. リソース フィルターの動作を選択します。  *含める*を選択すると、選択したリソースが復元されます。  *除外*を選択した場合、選択したリソースは復元されません。
. リソースを選択するためのフィルターを定義するルールを追加するには、[*ルールの追加*] を選択します。リソースをフィルタリングするには、少なくとも 1 つのルールが必要です。
+
各ルールは、リソースの名前空間、ラベル、グループ、バージョン、種類などの基準でフィルタリングできます。

. 各ルールを保存するには、[*保存*] を選択します。
. 必要なルールをすべて追加したら、「*検索*」を選択して、フィルター条件に一致するバックアップ アーカイブ内の利用可能なリソースを表示します。
+

NOTE: 表示されるリソースは、クラスター上に現在存在するリソースです。

. 結果に満足したら、[次へ] を選択します。


--
====
[discrete]
===== 宛先設定

. デフォルトのストレージ クラスに復元するか、別のストレージ クラスに復元するかを選択します。
. オプションで、別のストレージ クラスに復元することを選択した場合は、各ソース ストレージ クラスに一致する宛先ストレージ クラスを選択します。
. *復元*を選択します。

