---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery の Web UI を使用して、Kubernetes アプリケーションのオンデマンド バックアップを手動で作成します。 
---
= Kubernetes アプリケーションを NetApp Backup and Recovery の Web UI を使用してバックアップする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ウェブUIを使用して、Kubernetesアプリケーションのオンデマンドバックアップを実行します。

.必要なNetApp Consoleロール
組織管理者またはSnapCenter管理者。link:reference-roles.html["NetApp Backup and Recoveryのアクセス ロールについて学習します"] 。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。



[[back-up-a-kubernetes-application]]
== Kubernetesアプリケーションをバックアップする

将来のバックアップとスナップショットのベースラインを確立するため、または最新のデータが保護されていることを確認するために、Kubernetes アプリケーションのバックアップを手動で作成します。

.手順
. NetApp Backup and Recoveryで、*Inventory* を選択します。
. Kubernetes インスタンスを選択し、*表示* を選択すると、そのインスタンスに関連付けられたリソースにアクセスできます。
. *アプリケーション*タブを選択します。
. アプリケーション一覧から、バックアップしたいアプリケーションを選択し、関連する「アクション」メニューを選択します。
. *今すぐバックアップ*を選択します。
. 正しいアプリケーションが選択されていることを確認してください。
. *バックアップ*を選択します。


.結果
コンソールはアプリケーションのバックアップを作成し、バックアップとリカバリの *監視* 領域に進行状況を表示します。バックアップは、アプリケーションに関連付けられた保護ポリシーに基づいて作成されます。
