---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: お客様のMicrosoft SQL Serverアプリケーションデータを、オンプレミスのONTAPシステムからAmazon Web Services、Microsoft Azure、またはStorageGRIDに保護するには、NetApp Backup and Recoveryを使用します。 
---
= NetApp Backup and Recoveryを使用してMicrosoft SQL Serverワークロードを保護する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
オンプレミス ONTAP システムの Microsoft SQL Server データベースを、NetApp Backup and Recovery を使用して AWS、Azure、または StorageGRID にバックアップします。プライマリ ストレージでのスナップショット、セカンダリ システムへのレプリケーション、オブジェクト ストレージへのコピーを含む 3-2-1 バックアップ戦略を実装します。

NetApp Backup and Recovery は、 NetApp SnapMirrorを使用してスナップショットを作成し、それをバックアップの場所に転送することでバックアップを同期します。

データを保護するには、以下のワークフローを使用してください。

* link:concept-start-prereq-snapcenter-import.html["SnapCenterからインポートする場合の追加項目を構成する"]
* link:br-start-discover.html["Microsoft SQL Server ワークロードを検出し、オプションでSnapCenterリソースをインポートします"]
* link:br-use-mssql-backup.html["ローカルONTAPプライマリ ストレージ上のローカル スナップショットを使用してワークロードをバックアップします。"]
* link:br-use-mssql-backup.html["ワークロードをONTAPセカンダリストレージに複製する"]
* link:br-use-mssql-backup.html["ワークロードをオブジェクトストアの場所にバックアップする"]
* link:br-use-mssql-backup.html["今すぐワークロードをバックアップ"]
* link:br-use-mssql-restore.html["ワークロードを復元する"]
* link:br-use-mssql-clone.html["クローンワークロード"]
* link:br-use-manage-inventory.html["ワークロードのインベントリを管理する"]
* link:br-use-manage-snapshots.html["スナップショットを管理する"]


ワークロードをバックアップするには、バックアップおよび復元操作を管理するポリシーを作成します。見るlink:br-use-policies-create.html["ポリシーを作成"]詳細についてはこちらをご覧ください。

.サポートされているバックアップ先
NetApp Backup and Recovery は、以下のソースシステムから、パブリッククラウドおよびプライベートクラウド上のリストされたセカンダリ システムおよびオブジェクトストアへの Microsoft SQL Server インスタンスおよびデータベースのバックアップをサポートします。スナップショットはソースシステムに残ります。

[cols="33,33,33"]
|===
| ソースシステム | セカンダリ システム（レプリケーション） | 宛先オブジェクトストア（バックアップ） 


| AWS のCloud Volumes ONTAP | AWS オンプレミスONTAPシステムのCloud Volumes ONTAP | Amazon S3 ONTAP S3 


| Azure のCloud Volumes ONTAP | Azure のCloud Volumes ONTAPオンプレミスONTAPシステム | Azure ブロブONTAP S3 


| オンプレミスのONTAPシステム | Cloud Volumes ONTAPオンプレミスONTAPシステム | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA 
|===
.サポートされている復元先
プライマリストレージ、セカンダリ システム（複製ボリューム）、またはオブジェクトストレージ（バックアップファイル）に存在するバックアップから、Microsoft SQL Server のインスタンスとデータベースを以下の宛先システムに復元できます。スナップショットはソースシステム上に保存され、同じシステムにのみ復元できます。

[cols="33,33,33"]
|===
2+| バックアップファイルの場所から | 宛先システムへ 


| *オブジェクトストア（バックアップ）* | *セカンダリ システム（レプリケーション）* |  


| Amazon S3 | AWS オンプレミスONTAPシステムのCloud Volumes ONTAP | Cloud Volumes ONTAP AWS オンプレミス ONTAP システム ONTAP S3 


| Azure ブロブ | Azure のCloud Volumes ONTAPオンプレミスONTAPシステム | Azure のCloud Volumes ONTAPオンプレミスのONTAPシステムONTAP S3 


| StorageGRID | Cloud Volumes ONTAPオンプレミスONTAPシステム | オンプレミスのONTAPシステムONTAP S3 
|===

NOTE: 「オンプレミスのONTAPシステム」への参照には、 FASとAFFシステムが含まれます。
