---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recoveryを使用して KVM ワークロードを保護します。 
---
= NetApp Backup and Recoveryを使用して KVM 仮想マシンを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recoveryを使用して、スナップショット、セカンダリ ストレージに複製された保護グループ バックアップ、またはオブジェクト ストレージに保存されたバックアップから KVM 仮想マシンを復元します。

.これらの場所から復元
異なる開始場所から仮想マシンを復元できます。

* プライマリロケーション（ローカルスナップショット）からの復元
* セカンダリストレージ上の複製されたリソースから復元する
* オブジェクトストレージバックアップからの復元


.これらのポイントに復元する
以下のポイントまでデータを復元できます:

* 元の場所に復元する
* 別の場所に復元する


.オブジェクトストレージからの復元に関する考慮事項
オブジェクト ストレージでバックアップ ファイルを選択し、そのバックアップに対してランサムウェア保護がアクティブになっている場合（バックアップ ポリシーで Datalock とランサムウェア保護を有効にした場合）、データのリストア前にバックアップ ファイルに対して追加の整合性チェックを実行するように求められます。スキャンを実行することを推奨します。


TIP: バックアップ ファイルの内容にアクセスするには、クラウド プロバイダーから追加の送信コストが発生します。



[[how-restoring-virtual-machines-works]]
== 仮想マシンの復元の仕組み

仮想マシンを復元すると、次のことが起こります。

* ローカル バックアップ ファイルからワークロードを復元すると、 NetApp Backup and Recovery はバックアップのデータを使用して新しいリソースを作成します。
* レプリケートされた VM から復元する場合は、元のシステムまたはオンプレミスのONTAPシステムに復元できます。
* オブジェクト ストレージからバックアップを復元する場合、データを元のシステムまたはオンプレミスのONTAPシステムに復元できます。


復元ページから、仮想マシンの正確な名前、保存場所、最後に正常に動作していた日付を覚えていなくても、仮想マシンを復元できます。フィルタを使用してスナップショットを検索できます。



[[restore-kvm-virtual-machines]]
== KVM仮想マシンを復元する

「復元」メニューを使用して、KVM仮想マシンを復元します。スナップショットは、名前で検索するか、フィルタを使用して検索できます。

*必要なコンソール ロール* バックアップおよびリカバリのスーパー管理者またはバックアップおよびリカバリの復元管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

.手順
. NetApp Consoleメニューから、*保護 > バックアップとリカバリ* を選択します。
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*KVM* を選択します。
. 復元する VM の名前を入力するか、復元するリソースが配置されている VM ホストまたはストレージ プールをフィルターします。
+
検索条件に一致するスナップショットのリストが表示されます。

. 復元したいスナップショットの*復元*ボタンを選択します。
+
可能な復元ポイントのリストが表示されます。

. 使用する復元ポイントを選択します。
. スナップショットのソースの場所を選択します。
. 続行するには、[次へ] を選択します。
. 復元先と設定を選択します。
+
[discrete]
===== 目的地の選択

+
[role="tabbed-block"]
====
.元の場所へのリストア
--
.. *元の場所* ペインを選択します。
.. *Post-restore options* セクションで、 *Restart virtual machine* オプションを有効にすると、リストア処理の完了後に VM が再起動されます。


--
.別の場所へのリストア
--
.. *代替の場所* ペインを選択します。
.. *Cloudstack settings* セクションで、次の情報を入力します。
+
*** * ゾーン * ：リストからデスティネーション CloudStack ゾーンを選択します。
*** *Pod*：リストから選択したゾーン内のデスティネーション Pod を選択します。
*** *クラスター*：リストから選択したポッド内のデスティネーション クラスタを選択します。
*** *Host*：リストからクラスタ内のデスティネーションホストを選択します。
*** * ストレージプール * ：リストからデスティネーションストレージプールを選択します（デスティネーションボリュームはここに配置する必要があります）。
*** *Network*: リストアされた VM が接続されるネットワークを選択します。
*** *VM名*：復元するVMの名前を入力してください。
*** *表示名*：Backup and Recoveryでこの仮想マシンに表示される名前を入力します。
*** *Storage Pool Path*：VM ボリュームを格納するストレージプールパスを入力します。


.. *Select service offering* リストから、希望するリソース割り当てレベルを定義するサービスオファリングを選択します。
.. *Forced* オプションを有効にすると、VM の NIC MAC アドレスが 1 つ以上すでに存在する場合でも、リストアされた VM をインポートできます。MAC アドレスがすでに存在する場合は、その NIC 用に新しい MAC アドレスが生成されます。
.. *復元後のオプション*セクションで、次のオプションを検討してください。
+
*** *仮想マシンの再起動*：このオプションを有効にすると、復元後に新しい仮想マシンが起動します。




--
====
. *復元*を選択します。

