---
sidebar: sidebar 
permalink: br-use-vmware-restore-vmdks-from-backups.html 
keywords:  
summary: 従来のVMまたはvVol VMのプライマリ バックアップまたはセカンダリ バックアップから、既存のVMDKのほか、削除や切断したVMDKをリストアできます。 
---
= バックアップから特定の仮想ディスクを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
従来の VM のプライマリ バックアップまたはセカンダリ バックアップから、既存の仮想ディスク (VMDK)、または削除あるいは切断された仮想ディスクを復元できます。これにより、特定の VM データまたはアプリケーションのみを復元できるため、特定のデータのみが影響を受ける状況では、VM 全体とそれに関連付けられたすべての仮想ディスクを復元する必要がなくなります。仮想ディスクが復元されると、元の VM に接続され、使用できるようになります。

VM 上の 1 つ以上の仮想マシン ディスク (VMDK) を同じデータストアまたは異なるデータストアに復元できます。


TIP: NFS環境でのリストア処理のパフォーマンスを向上させるには、VMwareアプリケーションのvStorage API for Array Integration（VAAI）を有効にします。

.開始する前に
* バックアップが存在している必要があります。
* 転送中のVMはリストアできません。
+
リストアするVMがvMotionまたはStorage vMotionの状態であってはいけません。



.タスク概要
* VMDKがVMから削除されているか切断されている場合、リストア処理によってVMDKがVMに接続されます。
* VMが配置されているFabricPoolのストレージ階層が使用できない場合、リストア処理が失敗することがあります。
* 接続処理とリストア処理では、デフォルトのSCSIコントローラを使用してVMDKが接続されます。ただし、NVMeディスクを使用してVMに接続されたVMDKがバックアップされる際、接続処理とリストア処理では、利用可能な場合はNVMeコントローラが使用されます。


.手順
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*VMware* を選択します。
. 復元するリソースの名前を入力するか、復元するリソースが配置されている vCenter、データセンター、またはデータストアでフィルタリングします。
+
検索条件に一致する仮想マシンのリストが表示されます。

. リストから復元する VM を見つけて、その VM のオプション メニュー ボタンを選択します。
. 表示されるメニューで、「仮想ディスクの復元」を選択します。
+
その仮想マシン上に作成されたスナップショット (復元ポイント) のリストが表示されます。デフォルトでは、[*時間枠*] ドロップダウンで選択した時間枠の最新のスナップショットが表示されます。

+
各スナップショットについて、*場所* 列の点灯したアイコンは、スナップショットが使用可能なストレージの場所 (プライマリ、セカンダリ、またはオブジェクト ストレージ) を示します。

. 復元するスナップショットのラジオ ボタンを有効にします。
. *次へ*を選択します。
+
スナップショットの場所のオプションが表示されます。

. スナップショットの復元先を選択します。
+
** *ローカル*: ローカルの場所からスナップショットを復元します。
** *セカンダリ*: リモート ストレージの場所からスナップショットを復元します。
** *オブジェクト ストア*: オブジェクト ストレージからスナップショットを復元します。
+
セカンダリ ストレージを選択した場合は、ドロップダウン リストから保存先の場所を選択します。



. *次へ*を選択します。
. 宛先設定と復元前および復元後のオプションを選択します。


[discrete]
===== 目的地の選択

[role="tabbed-block"]
====
.元の場所へのリストア
--
元の場所に復元する場合、宛先の vCenter、ESXi ホスト、データストア、または仮想ディスクの名前を変更することはできません。元の仮想ディスクは上書きされます。

. *元の場所* ペインを選択します。
. *宛先設定*セクションで、復元する仮想ディスクのチェックボックスをオンにします。
. 次のいずれかのオプションを選択します。
+
** *復元前オプション*セクション:
+
*** *プレスクリプト*: 復元操作を開始する前にカスタム スクリプトを実行して追加のタスクを自動化するには、このオプションを有効にします。実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。


** *復元後のオプション*セクション:
+
*** *Postscript*: 復元が完了した後にカスタム スクリプトを実行して追加のタスクを自動化するには、このオプションを有効にします。実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。




. *復元*を選択します。


--
.別の場所へのリストア
--
別の場所に復元する場合は、宛先データストアを変更できます。選択したデータストアに関係なく、復元操作後に仮想ディスクは元の VM に接続されます。

. *代替の場所* ペインを選択します。
. *宛先設定*セクションで、復元する仮想ディスクのチェックボックスをオンにします。
. 選択した仮想ディスクの場合:
+
.. 仮想ディスクの別のデータストア復元ターゲットを選択するには、「データストアの選択」を選択します。
.. *選択*を選択して選択を確認し、選択ウィンドウを閉じます。


. 次のいずれかのオプションを選択します。
+
** *復元前オプション*セクション:
+
*** *プレスクリプト*: 復元操作を開始する前にカスタム スクリプトを実行して追加のタスクを自動化するには、このオプションを有効にします。実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。


** *復元後のオプション*セクション:
+
*** *Postscript*: 復元が完了した後にカスタム スクリプトを実行して追加のタスクを自動化するには、このオプションを有効にします。実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。




. *復元*を選択します。


--
====