---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: ワークロードの健全性を監視することで、ワークロード保護に関する問題を認識し、解決するための手順を実行できるようになります。バックアップとリストアのステータスを表示し、 NetApp Backup and Recoveryダッシュボードに表示されるアラートに応答します。保護の概要、復元の概要、システムの概要などを確認できます。 
---
= NetApp Backup and Recoveryダッシュボードで保護の健全性を確認する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ワークロードの健全性を監視することで、ワークロード保護に関する問題を認識し、解決するための手順を実行できるようになります。 NetApp Backup and Recoveryダッシュボードでバックアップと復元のステータスを表示します。システムの概要、保護の概要、ジョブの概要、復元の概要などを確認できます。

*必要なNetApp Consoleロール* ストレージ ビューアー、バックアップおよびリカバリ スーパー管理者、バックアップおよびリカバリ バックアップ管理者、バックアップおよびリカバリ リストア管理者、バックアップおよびリカバリ クローン管理者、またはバックアップおよびリカバリ ビューアー ロール。詳細はこちらlink:reference-roles.html["バックアップとリカバリの役割と権限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

.手順
. NetApp Backup and Recoveryメニューから、*ダッシュボード* を選択します。
+
** 検出されたホストまたはVMの数
** 検出されたKubernetesクラスターの数
** オブジェクトストレージ上のバックアップ対象の数
** vCenterの数
** ONTAPのストレージクラスタの数






== 保護の概要を表示する

保護の概要で次の情報を確認します。

* 保護されているデータベース、VM、データストアと保護されていないデータベース、VM、データストアの合計数。
+

TIP: 保護されたデータベースとは、バックアップ ポリシーが割り当てられたデータベースです。保護されていないデータベースとは、バックアップ ポリシーが割り当てられていないデータベースです。

* 成功したバックアップ、警告のあったバックアップ、失敗したバックアップの数。
* バックアップ サービスによって検出された合計容量と、保護されている容量と保護されていない容量。  「*i*」アイコンにマウスを合わせると詳細が表示されます。




== 求人概要を見る

ジョブの概要で、完了したジョブ、実行中のジョブ、失敗したジョブの合計数を確認します。

.手順
. 各ジョブの配布について、フィルターを変更して、過去 30 日間、過去 7 日間、過去 24 時間、過去 1 年間などの日数に基づいて、失敗、実行中、完了の概要を表示します。
. *ジョブ監視の表示* を選択して、失敗したジョブ、実行中のジョブ、完了したジョブの詳細を表示します。




== 復元の概要を表示する

復元の概要で次の情報を確認します。

* 実行された復元ジョブの合計数
* 回復した容量の合計
* ローカル、セカンダリ、オブジェクト ストレージで実行された復元ジョブの数。グラフの上にマウスを移動すると詳細が表示されます。

