---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: WindowsゲストOSの仮想マシン ディスク（VMDK）からファイルやフォルダをリストアできます。 
---
= ゲストファイルとフォルダを復元する際の要件と制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
WindowsゲストOSの仮想マシン ディスク（VMDK）からファイルやフォルダをリストアできます。



== ゲスト リストアのワークフロー

ゲストOSリストア処理には、次の手順が含まれます。

. 接続
+
仮想ディスクをゲスト VM に接続し、ゲスト ファイルの復元セッションを開始します。

. 待機
+
参照および復元する前に、接続操作が完了するまで待機してください。アタッチ操作が完了すると、ゲスト ファイルの復元セッションが自動的に作成されます。

. ファイルまたはフォルダの選択
+
VMDK ファイルを参照し、復元する 1 つ以上のファイルまたはフォルダーを選択します。

. リストア
+
選択したファイルまたはフォルダを指定した場所にリストアします。





== ゲスト ファイルとフォルダをリストアするための前提条件

Windows ゲスト OS 上の VMDK からファイルまたはフォルダーを復元する前に、すべての要件を確認してください。

* VMware Toolsがインストールされ、実行されている必要があります。
+
NetApp Backup and Recovery は、VMware ツールからの情報を使用して、VMware ゲスト OS への接続を確立します。

* Windows ゲスト OS は Windows Server 2008 R2 以降を実行している必要があります。
+
サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool（IMT）"^] 。

* ターゲット VM の資格情報には、ユーザー名が「Administrator」の組み込みドメインまたはローカル管理者アカウントが使用されます。復元操作を開始する前に、仮想ディスクを接続する VM の資格情報を構成します。アタッチ操作と復元操作の両方に資格情報が必要です。ワークグループ ユーザーは、組み込みのローカル管理者アカウントを使用できます。
+

IMPORTANT: 組み込みの管理者アカウントではなく、VM内の管理者権限を持つアカウントを使用する必要がある場合は、ゲストVMのUACを無効にする必要があります。

* 復元元のバックアップ スナップショットと VMDK を知っておく必要があります。
+
NetApp Backup and Recovery、復元するファイルまたはフォルダの検索はサポートされていません。始める前に、スナップショット内のファイルまたはフォルダーと対応する VMDK の場所を知っておく必要があります。

* 接続する仮想ディスクは、NetApp Backup and Recoveryバックアップに含まれている必要があります。
+
復元するファイルまたはフォルダを含む仮想ディスクは、NetApp Backup and Recoveryを使用して実行された VM バックアップに含まれている必要があります。



* 英語のアルファベット以外を使った名前のファイルの場合は、単一のファイルとしてではなく、ディレクトリにリストアする必要があります。
+
日本語の漢字など、アルファベット以外の名前のファイルをリストアするには、ファイルが配置されているディレクトリをリストアします。





== ゲスト ファイル リストアに関する制限事項

ゲスト OS からファイルまたはフォルダーを復元する前に、機能の制限に注意する必要があります。

* ゲストOS内でダイナミック ディスク タイプをリストアすることはできません。
* 暗号化されたファイルまたはフォルダをリストアした場合、暗号化属性は保持されません。
* ファイルまたはフォルダを暗号化されたフォルダにリストアすることはできません。
* 隠しファイルとフォルダーはファイル参照ページに表示されますが、フィルタリングすることはできません。
* LinuxゲストOSからはリストアできません。
+
LinuxゲストOSを実行しているVMからファイルやフォルダをリストアすることはできません。ただし、VMDKを接続し、ファイルとフォルダを手動でリストアすることもできます。サポートされているゲストOSの最新情報については、 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool（IMT）"^] 。

* NTFSファイルシステムからFATファイルシステムにリストアすることはできません。
+
NTFS形式からFAT形式にリストアしようとした場合、FATファイルシステムはWindowsセキュリティ属性をサポートしていないため、NTFSセキュリティ記述子はコピーされません。

* クローニングされたVMDKまたは初期化されていないVMDKからゲスト ファイルをリストアすることはできません。
* ファイルのディレクトリ構造はリストアできません。
+
ネストされたディレクトリからファイルを復元する場合、システムはディレクトリ構造ではなくファイルのみを復元します。ディレクトリ ツリー全体を復元するには、最上位のディレクトリをコピーします。

* vVol VMから別のホストにゲスト ファイルをリストアすることはできません。
* 暗号化されたゲスト ファイルはリストアできません。

