---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: NetApp Backup and Recoveryを使用して Hyper-V ワークロードを保護します。 
---
= NetApp Backup and Recoveryを使用して Hyper-V ワークロードを復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recoveryを使用して、スナップショット、セカンダリ ストレージに複製されたワークロード バックアップ、またはオブジェクト ストレージに保存されたバックアップから Hyper-V ワークロードを復元します。

.これらの場所から復元
異なる開始場所からワークロードを復元できます。

* プライマリロケーション（ローカルスナップショット）からの復元
* セカンダリストレージ上の複製されたリソースから復元する
* オブジェクトストレージバックアップからの復元


.これらのポイントに復元する
以下のポイントまでデータを復元できます:

* 元の場所に復元する


.オブジェクトストレージからの復元に関する考慮事項
オブジェクト ストレージ内のバックアップ ファイルを選択し、そのバックアップに対してランサムウェア保護がアクティブになっている場合 (バックアップ ポリシーで DataLock と Ransomware Resilience を有効にしている場合)、データを復元する前に、バックアップ ファイルに対して追加の整合性チェックを実行するように求められます。スキャンを実行することをお勧めします。


TIP: バックアップ ファイルの内容にアクセスするには、クラウド プロバイダーから追加の送信コストが発生します。



== ワークロードの復元の仕組み

ワークロードを復元すると、次のことが起こります。

* ローカル バックアップ ファイルからワークロードを復元すると、 NetApp Backup and Recovery はバックアップのデータを使用して新しいリソースを作成します。
* 複製されたワークロードから復元する場合、ワークロードを元のシステムまたはオンプレミスのONTAPシステムに復元できます。


[復元] ページ (検索と復元とも呼ばれます)* からは、リソースの正確な名前、リソースが存在する場所、リソースが最後に良好な状態であった日付を覚えていなくても、リソースを復元できます。フィルターを使用してスナップショットを検索できます。



== 復元オプション（検索と復元）からワークロード データを復元します。

復元オプションを使用して Hyper-V ワークロードを復元します。スナップショットは、名前またはフィルターを使用して検索できます。

*必要なコンソール ロール* バックアップおよびリカバリのスーパー管理者またはバックアップおよびリカバリの復元管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^] 。

.手順
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*Hyper-V* を選択します。
. 復元するリソースの名前を入力するか、復元するリソースが配置されている VM 名、VM ホスト、またはストレージ プールでフィルターします。
+
検索条件に一致するスナップショットのリストが表示されます。

. 復元したいスナップショットの*復元*ボタンを選択します。
+
可能な復元ポイントのリストが表示されます。

. 使用する復元ポイントを選択します。
. スナップショットのソースの場所を選択します。
. *完了*または*次へ*を選択して、復元先設定ページに進みます。
+
次に、宛先設定と復元前および復元後のオプションを選択できます。



[discrete]
===== 目的地の選択

. 宛先設定と復元前および復元後のオプションを選択します。


[role="tabbed-block"]
====
.元の場所へのリストア
--
. *クイック復元を有効にする*: クイック復元操作を実行するにはこれを選択します。復元されたボリュームとデータはすぐに利用できるようになります。クイック リストア プロセス中はデータへのアクセスが通常よりも遅くなる可能性があるため、高パフォーマンスが必要なボリュームではこれを使用しないでください。
. *復元前オプション*: 復元操作の前に実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。
. *復元後のオプション*:
+
** *VM の再起動*: 復元操作が完了し、復元後のスクリプトが適用された後に VM を再起動するには、これを選択します。
** *Postscript*: 復元操作後に実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。


. *通知*セクション:
+
** *電子メール通知を有効にする*: 復元操作に関する電子メール通知を受信し、受信する通知の種類を指定するには、これを選択します。


. *復元*を選択します。


--
.別の場所へのリストア
--
Hyper-V ワークロード プレビューでは使用できません。

--
====