---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recoveryを使用して、オンプレミスのONTAPシステムから Amazon Web Services、Microsoft Azure、またはStorageGRIDに至るまで、Microsoft SQL Server アプリケーション データを保護します。 
---
= NetApp Backup and Recoveryを使用した Microsoft SQL ワークロードの保護の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recoveryを使用して、オンプレミスのONTAPシステムから AWS、Azure、またはStorageGRIDに Microsoft SQL Server アプリケーション データをバックアップします。システムはポリシーに従って、クラウド アカウントにバックアップを自動的に作成して保存します。  3-2-1 戦略を使用します。つまり、データの 3 つのコピーを 2 つのストレージ システムに保存し、1 つのコピーをクラウドに保存します。

3-2-1 アプローチの利点は次のとおりです。

* 複数のデータ コピーにより、内部および外部のサイバー セキュリティの脅威から保護されます。
* 異なるタイプのメディアを使用すると、1 つのタイプに障害が発生した場合でも回復しやすくなります。
* オンサイト コピーから迅速に復元し、オンサイト コピーが侵害された場合はオフサイト コピーを使用できます。


NetApp Backup and Recovery は、 NetApp SnapMirrorを使用してスナップショットを作成し、それをバックアップの場所に転送することでバックアップを同期します。

データを保護するために、次の操作を実行できます。

* link:concept-start-prereq-snapcenter-import.html["SnapCenterからインポートする場合の追加項目を構成する"]
* link:br-start-discover.html["Microsoft SQL Server ワークロードを検出し、オプションでSnapCenterリソースをインポートします"]
* link:br-use-mssql-backup.html["ローカルONTAPプライマリ ストレージ上のローカル スナップショットを使用してワークロードをバックアップします。"]
* link:br-use-mssql-backup.html["ワークロードをONTAPセカンダリストレージに複製する"]
* link:br-use-mssql-backup.html["ワークロードをオブジェクトストアの場所にバックアップする"]
* link:br-use-mssql-backup.html["今すぐワークロードをバックアップ"]
* link:br-use-mssql-restore.html["ワークロードを復元する"]
* link:br-use-mssql-clone.html["クローンワークロード"]
* link:br-use-manage-inventory.html["ワークロードのインベントリを管理する"]
* link:br-use-manage-snapshots.html["スナップショットを管理する"]


ワークロードをバックアップするには、バックアップおよび復元操作を管理するポリシーを作成します。見るlink:br-use-policies-create.html["ポリシーを作成"]詳細についてはこちらをご覧ください。

.サポートされているバックアップ先
NetApp Backup and Recovery を使用すると、Microsoft SQL Server インスタンスとデータベースを次のソース システムから次のセカンダリ システムおよびパブリック クラウド プロバイダーとプライベート クラウド プロバイダーのオブジェクト ストレージにバックアップできます。スナップショットはソース システムに存在します。

[cols="33,33,33"]
|===
| ソースシステム | セカンダリシステム（レプリケーション） | 宛先オブジェクトストア（バックアップ） 


| AWS のCloud Volumes ONTAP | AWS オンプレミスONTAPシステムのCloud Volumes ONTAP | Amazon S3 ONTAP S3 


| Azure のCloud Volumes ONTAP | Azure のCloud Volumes ONTAPオンプレミスONTAPシステム | Azure ブロブONTAP S3 


| オンプレミスのONTAPシステム | Cloud Volumes ONTAPオンプレミスONTAPシステム | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA 
|===
.サポートされている復元先
プライマリ ストレージまたはセカンダリ システム (複製されたボリューム) またはオブジェクト ストレージ (バックアップ ファイル) にあるバックアップから、Microsoft SQL Server インスタンスとデータベースを次のシステムに復元できます。スナップショットはソース システム上に存在し、同じシステムにのみ復元できます。

[cols="33,33,33"]
|===
2+| バックアップファイルの場所から | 宛先システムへ 


| *オブジェクトストア（バックアップ）* | *セカンダリシステム（レプリケーション）* |  


| Amazon S3 | AWS オンプレミスONTAPシステムのCloud Volumes ONTAP | AWS オンプレミスのONTAPシステムONTAP S3 の Cloud Volumes 


| Azure ブロブ | Azure のCloud Volumes ONTAPオンプレミスONTAPシステム | Azure のCloud Volumes ONTAPオンプレミスのONTAPシステムONTAP S3 


| StorageGRID | Cloud Volumes ONTAPオンプレミスONTAPシステム | オンプレミスのONTAPシステムONTAP S3 
|===

NOTE: 「オンプレミスのONTAPシステム」への参照には、 FASとAFFシステムが含まれます。
