---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recoveryを使用してOracle Databaseワークロードを保護します。 
---
= Oracle DatabaseワークロードをNetApp Backup and Recoveryで復元する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
スナップショット、セカンダリ システム上のレプリケートされたバックアップ、またはオブジェクトストレージに保存されているバックアップから Oracle Database ワークロードを復元するには、NetApp Backup and Recovery を使用します。

.これらの場所から復元
異なる開始場所からデータベースを復元できます。

* プライマリロケーション（ローカルスナップショット）からの復元
* セカンダリストレージ上の複製されたリソースから復元する
* オブジェクトストレージバックアップからの復元


.これらのポイントに復元する
データを元の場所に復元することはできますが、このプライベート プレビュー リリースでは別の場所に復元することはできません。

* 元の場所に復元する




[[how-oracle-database-restore-works]]
== Oracleデータベースのリストアの仕組み

Oracle Database のワークロードを復元すると、次のことが発生します：

* ローカル スナップショットからデータベースを復元すると、 NetApp Backup and Recovery はバックアップのデータを使用して新しいリソースを作成します。
* 複製されたストレージから復元する場合は、元の場所に復元できます。
* オブジェクト ストレージからバックアップを復元する場合、データをソース ストレージまたはオンプレミスのONTAPシステムに復元し、そこからデータベースを回復できます。


[復元] ページ (検索と復元とも呼ばれます) からは、データベースの正確な名前、データベースが存在する場所、データベースが最後に正常な状態であった日付を覚えていなくても、データベースを復元できます。フィルターを使用してデータベースを検索できます。



[[restore-an-oracle-database]]
== Oracleデータベースを復元する

必要に応じて、Oracleデータベースを特定の時点、特定のシステム変更番号（SCN）、または最後に正常に動作していた状態に復元できます。また、スナップショットからデータベースを復元して、自動リカバリプロセスをスキップすることもできます。たとえば、手動でリカバリを実行したい場合などに利用できます。データベースは、その名前で検索することも、特定のフィルターを使用して検索することもできます。

*必須NetApp Console ロール* バックアップおよびリカバリのスーパー管理者、またはバックアップおよびリカバリのリストア管理者ロール。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するNetApp Consoleのアクセスロールについて学習します"^]

.手順
. NetApp Consoleメニューから、*保護 > バックアップとリカバリ* を選択します。
. NetApp Backup and Recoveryメニューから、[復元] を選択します。
. 名前検索フィールドの右側にあるドロップダウン リストから、*Oracle* を選択します。
. 復元するデータベースの名前を入力するか、復元するデータベースが配置されているデータベース ホストをフィルターします。
+
検索条件に一致するスナップショットのリストが表示されます。

. 復元するデータベースの*復元*ボタンを選択します。
. 復元オプションを選択します:
+
[role="tabbed-block"]
====
.特定の時点に復元する
--
.. *特定の時点に復元*を選択します。
.. *次へ*を選択します。
.. ドロップダウンから日付を選択し、「*検索*」を選択します。
+
指定された日付に一致するスナップショットのリストが表示されます。



--
.特定のシステム変更番号 (SCN) に復元する
--
.. *特定のシステム変更番号 (SCN) に復元*を選択します。
.. *次へ*を選択します。
.. 復元ポイントとして使用する SCN を入力し、[検索] を選択します。
+
指定された SCN に一致するスナップショットのリストが表示されます。



--
.最新のバックアップ（最後の正常な状態）に復元する
--
.. *最新のバックアップに復元*を選択します。
.. *次へ*を選択します。
+
最新の完全バックアップとログバックアップが表示されます。



--
.リカバリなしでスナップショットから復元
--
.. *リカバリなしでスナップショットから復元*を選択します。
.. *次へ*を選択します。
+
一致するスナップショットが表示されます。



--
====
. スナップショットのソースの場所を選択します。
. 続行するには、[次へ] を選択します。
. 復元先と設定を選択します。


[discrete]
===== 目的地の選択

[role="tabbed-block"]
====
.元の場所へのリストア
--
[NOTE]
====
PDBまたはPDBテーブルスペースを特定のポイントインタイムまたはSCNにリストアする場合：

* PDBを1つだけ選択してください。ポイントインタイムリカバリは、複数のPDBのリストアとは互換性がありません。
* PDB$SEEDはポイントインタイムリカバリに選択できません。
* 制御ファイルのリストアは、PDBまたはテーブルスペースのポイントインタイムリカバリと組み合わせることはできません。
* データバックアップと必要なログバックアップがカタログ化されていることを確認してください。


====
. *宛先設定*:
. 復元する項目を選択してください：
+
** *[すべてのデータファイル]* を選択すると、データベース全体またはコンテナデータベース（CDB）が復元されます。
** コンテナ内の他の PDB に影響を与えることなく、CDB から 1 つ以上の PDB を復元するには、*プラガブル データベース （PDB）* を選択します。次に、リストから PDB を選択します。
** 特定の PDB テーブルスペースを復元するには、*「プラガブル データベース （PDB） テーブルスペース」*（CDB 以外のデータベースの場合は *「テーブルスペース」* と表示されます）を選択します。次に、PDB とテーブルスペースを選択します。


. 必要に応じて、*制御ファイル*オプションを有効にすると、データベースの制御ファイルも復元されます。このオプションは、PDBまたはPDBテーブルスペースのポイントインタイムまたはSCNリカバリには使用できません。
. 必要に応じて、「復元およびリカバリに必要な場合にデータベースの状態を変更する」オプションを有効にすると、Backup and Recoveryがリカバリの種類に応じてデータベースの状態を管理できるようになります。
. オプションとして、「強制インプレース復元」オプションを有効にすると、SAN/ASMデータベースに対して、外部ファイルの検証チェックをスキップして、より高速な復元方法を使用できます。データベースとASM ディスク グループは、バックアップ作成時点の状態に復元されます。
. PDBまたはPDBテーブルスペースを特定のポイントインタイムまたはSCNに復元する場合は、外部アーカイブログファイルの場所を指定してください。RMANがリカバリを実行するための補助インスタンスを作成する場所を入力してください。「/」で始まるファイルシステムパス、または「+」で始まるASM ディスク グループを入力してください。テキスト入力フィールドの横にある「プラス」ボタンと「マイナス」ボタンを使用して、場所を追加または削除します。
. オプションとして、*リカバリ後にデータベースまたはコンテナデータベースをREAD-WRITEモードで開く*を有効にすると、復元後にデータベースをREAD-WRITEモードで開くことができます。これにより、復元されたテーブルスペースがオンラインになります。
. *前書きと後書き*：
+
** *Prescript*：必要に応じて、このオプションを有効にして、リストア操作の前に実行するスクリプトの完全パスと、そのスクリプトが受け取る引数を入力します。
** *Postscript*: 必要に応じて、このオプションを有効にし、復元操作後に実行するスクリプトの完全なパスと、スクリプトが受け取る引数を入力します。


. スクリプトのタイムアウト値を選択してください。スクリプトがこの時間内に実行されなかった場合でも、復元処理は続行されます。
. *復元*を選択します。


--
.別の場所へのリストア
--
このプレビューリリースでは、Oracle Database ワークロードでは利用できません。

--
====