---
sidebar: sidebar 
permalink: prev-reference-azure-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery は、 1 つの Azure アーカイブ アクセス層とほとんどのリージョンをサポートします。 
---
= NetApp Backup and Recoveryでサポートされている Azure アーカイブ アクセス層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery は、 1 つの Azure アーカイブ アクセス層とほとんどのリージョンをサポートします。

[]
====

NOTE: NetApp Backup and Recovery UIのバージョンを切り替えるには、link:br-start-switch-ui.html["以前のNetApp Backup and RecoveryUIに切り替える"] 。

====


== NetApp Backup and Recoveryでサポートされている Azure BLOB アクセス層

バックアップ ファイルは最初に作成されると、_Cool_ アクセス層に保存されます。この層は、アクセス頻度は低いが、必要なときにすぐにアクセスできるデータを保存するように最適化されています。

ソース クラスターでONTAP 9.10.1 以降が実行されている場合は、コストをさらに最適化するために、一定の日数 (通常は 30 日以上) 後にバックアップを _Cool_ ストレージから _Azure Archive_ ストレージに階層化することを選択できます。この層のデータは必要なときにすぐにアクセスできず、取得コストも高くなります。そのため、アーカイブされたバックアップ ファイルからデータを復元する必要がある頻度を考慮する必要があります。アーカイブ ストレージからのデータの復元については、このページのセクションを参照してください。

このタイプのライフサイクル ルールを使用してNetApp Backup and Recoveryを構成する場合は、Azure アカウントでコンテナーを設定するときにライフサイクル ルールを構成しないでください。

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Azure BLOB アクセス層について学ぶ"^]。



== アーカイブストレージからデータを復元する

古いバックアップ ファイルをアーカイブ ストレージに保存するとクール ストレージよりもはるかに安価になりますが、復元操作のために Azure アーカイブ内のバックアップ ファイルのデータにアクセスすると、時間がかかり、コストも高くなります。

Azure Archive からデータを復元するにはどれくらいの費用がかかりますか?:: Azure アーカイブからデータを取得するときに選択できる復元優先順位は 2 つあります。
+
--
* *高*: 最も高速な検索、高コスト
* *標準*: 検索速度は遅いが、コストは低い


それぞれの方法では、GB あたりの取得料金とリクエストあたりの料金が異なります。  Azureリージョン別のAzure Archiveの詳細な料金については、 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Azure 料金ページ"^] 。

--



NOTE: Azure からStorageGRIDシステムにデータを復元する場合、高優先度はサポートされません。

Azure Archive にアーカイブされたデータを復元するにはどのくらいの時間がかかりますか?:: 復元時間は 2 つの部分で構成されます。
+
--
* *取得時間*: アーカイブされたバックアップ ファイルを Azure アーカイブから取得し、クール ストレージに配置する時間。これは「再水和」時間と呼ばれることもあります。取得時間は、選択した復元優先度によって異なります。
+
** *高*: < 1時間
** *標準*: 15時間未満


* *復元時間*: クール ストレージ内のバックアップ ファイルからデータを復元する時間。今回は、アーカイブ層を使用していない場合の、クール ストレージからの通常の復元操作と変わりません。


Azure アーカイブの取得オプションの詳細については、以下を参照してください。 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/#faq["このAzure FAQ"^] 。

--

