---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp NetApp Backup and Recoveryを使用して VMware ワークロードを保護します。 
---
= NetApp Backup and Recoveryでデータストアをバックアップするためのポリシーを作成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ポリシーを作成するか、 NetApp Backup and Recoveryで使用可能な次の定義済みポリシーのいずれかを使用することができます。

[]
====
*注意* NetApp Backup and Recoveryのワークロードを切り替えるには、link:br-start-switch-ui.html["さまざまなNetApp Backup and Recoveryワークロードに切り替える"] 。

====
.開始する前に
* 定義済みのポリシーを編集したくない場合は、ポリシーを作成する必要があります。
* バックアップをオブジェクト ストアからアーカイブ ストレージに移動するには、 ONTAP 9.10.1 以降を実行し、Amazon Web Services または Microsoft Azure をクラウド プロバイダーにする必要があります。
* 各クラウド プロバイダーのアーカイブ アクセス層を構成する必要があります。


.タスク概要
NetApp Consoleでは、次の定義済みポリシーを使用できます。

|===
| ポリシー名 | ラベル | 保持価値 


 a| 
1年間の日次LTR（長期保持）
 a| 
日次
 a| 
366



 a| 
5年間の毎日のLTR
 a| 
日次
 a| 
1830



 a| 
7年間の週次LTR
 a| 
週次
 a| 
370



 a| 
10年間の月払いLTR
 a| 
毎月
 a| 
120

|===
.手順
. [仮想マシン] ページの [設定] ドロップダウン リストから [*ポリシー*] を選択します。
. *ポリシーの作成*を選択します。
. 「ポリシーの詳細」セクションで、ポリシー名を指定します。
. 「保持」セクションで、保持タイプの 1 つを選択し、保持するバックアップの数を指定します。
. バックアップ ストレージ ソースとしてプライマリまたはセカンダリを選択します。
. (オプション) コストの最適化のために、一定の日数後にバックアップをオブジェクト ストアからアーカイブ ストレージに移動する場合は、[バックアップをアーカイブに階層化] チェックボックスをオンにして、バックアップをアーカイブするまでの日数を入力します。
. *作成*を選択します。
+

NOTE: データストアに関連付けられているポリシーを編集または削除することはできません。


