---
sidebar: sidebar 
permalink: prev-reference-azure-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery は、 1 つの Azure アーカイブ アクセス層とほとんどのリージョンをサポートします。 
---
= NetApp Backup and Recoveryでサポートされている Azure アーカイブ アクセス層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この情報を使用して、NetApp Backup and Recovery がサポートする Azure アーカイブ層を理解してください。アーカイブされたバックアップのリストアコストと取得時間も確認できます。



[[supported-azure-blob-access-tiers-for-netapp-backup-and-recovery]]
== NetApp Backup and Recoveryでサポートされている Azure BLOB アクセス層

バックアップファイルが最初に作成されると、_Cool_ アクセス層に保存されます。この層は、アクセス頻度の低いデータの保存に最適化されていますが、必要なときにすぐにアクセスできます。

ソース クラスターでONTAP 9.10.1 以降が実行されている場合は、コストをさらに最適化するために、一定の日数 (通常は 30 日以上) 後にバックアップを _Cool_ ストレージから _Azure Archive_ ストレージに階層化することを選択できます。この層のデータは必要なときにすぐにアクセスできず、取得コストも高くなります。そのため、アーカイブされたバックアップ ファイルからデータを復元する必要がある頻度を考慮する必要があります。アーカイブ ストレージからのデータの復元については、このページのセクションを参照してください。

このタイプのライフサイクル ルールを使用してNetApp Backup and Recoveryを構成する場合は、Azure アカウントでコンテナーを設定するときにライフサイクル ルールを構成しないでください。

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Azure BLOB アクセス層について学ぶ"^]。



[[restore-data-from-archival-storage]]
== アーカイブストレージからデータを復元する

古いバックアップ ファイルをアーカイブ ストレージに保存するとクール ストレージよりもはるかに安価になりますが、復元操作のために Azure アーカイブ内のバックアップ ファイルのデータにアクセスすると、時間がかかり、コストも高くなります。

Azure Archive からデータを復元するにはどれくらいの費用がかかりますか?:: Azure アーカイブからデータを取得するときに選択できる復元優先順位は 2 つあります。
+
--
* *高*: 最も高速な検索、高コスト
* *標準*: 検索速度は遅いが、コストは低い


それぞれの方法では、GB あたりの取得料金とリクエストあたりの料金が異なります。  Azureリージョン別のAzure Archiveの詳細な料金については、 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Azure 料金ページ"^] 。

--



NOTE: Azure から StorageGRID システムにデータをリストアする場合、高優先度はサポートされていません。

Azure Archive にアーカイブされたデータを復元するにはどのくらいの時間がかかりますか?:: 復元時間は 2 つの部分で構成されます。
+
--
* *取得時間*: アーカイブされたバックアップ ファイルを Azure アーカイブから取得し、クール ストレージに配置する時間。これは「再水和」時間と呼ばれることもあります。取得時間は、選択した復元優先度によって異なります。
+
** *高*: < 1時間
** *標準*: 15時間未満


* *復元時間*: クール ストレージ内のバックアップ ファイルからデータを復元する時間。今回は、アーカイブ層を使用していない場合の、クール ストレージからの通常の復元操作と変わりません。
+
Azure アーカイブの取得オプションの詳細については、以下を参照してください。 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/#faq["このAzure FAQ"^] 。



--


[NOTE]
====
アーカイブストレージからボリュームやファイルを復元するには、追加の時間がかかる場合があります。バックアップとリカバリが選択された優先度に基づいて復元を再試行している間、ジョブモニターではジョブは「進行中」のままになります。復元処理は「ジョブモニター」で監視します。すべての再試行後、ジョブが「完了」または「失敗」などの最終ステータスに達すると、復元処理は完了します。最終的にジョブが失敗しない限り、別の復元を開始しないでください。

====