---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recoveryを使用してVMwareワークロードを保護します。 
---
= NetApp Backup and Recoveryを使用して、オンプレミスのONTAPデータをS3互換ストレージにバックアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
いくつかの手順を実行して、NetApp Backup and Recovery を使用して、プライマリオンプレミス ONTAP システムからボリュームデータのバックアップを開始します。バックアップをセカンダリ ONTAP ストレージシステム（レプリケートされたボリューム）、S3 互換ストレージシステムのバケット、またはその両方に送信できます。



[[verify-support-for-your-configuration]]
== 構成のサポートを確認する

S3互換ストレージへのボリュームのバックアップを開始する前に、サポートされている構成になっていることを確認するために、以下の要件をお読みください。

サポートされるONTAPバージョン:: ONTAP バージョン 9.17.1 以降が必要です。




[[supported-actions]]
=== サポートされているアクション

S3互換ストレージへのバックアップ時にサポートされている操作は以下のとおりです：

* オンプレミス ONTAP から サードパーティの S3 互換オブジェクトストアへの「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態およびアプリケーション整合性スナップショットのバックアップ
* コアデータ保護ワークフロー：バックアップ、リストア、およびバックアップ削除
* Wasabiオブジェクトストレージでテストおよび検証済み。また、MinIOおよびIBM Cloud Object Storageを使用した導入の成功事例もお客様から報告されています。
* NetAppサポート部門は、サードパーティ製のS3互換オブジェクトストアに関するすべてのサポートリクエストを受け付け、優先順位付けを行います。




[[unsupported-features-and-configurations]]
=== サポートされていない機能と構成

S3互換ストレージへのバックアップ時には、以下の機能および構成はサポートされません：

* Bring Your Own Bucket（BYOB）はサポートされていません
* バックアップポリシーでのDataLockの有効化はサポートされていません
* バックアップポリシーでのアーカイブモードの有効化はサポートされていません
* バケットレベルの暗号化オプションはサポートされていません
* MetroCluster 構成はサポートされていません
* クラウドベースの ONTAP 環境はサポートされていません。オンプレミスの ONTAP のみがサポートされています




[[caveats]]
=== 注意事項

S3互換ストレージにバックアップを行う際は、以下の点に注意してください：

* *パフォーマンスは保証されません*：NetApp製品はS3 APIのレイテンシとIOPSに影響を受けやすいです。サードパーティ製のオブジェクトストアは、同等のパフォーマンスを実現するために、AWS S3と同等のレイテンシとIOPSを提供する必要があります。NetAppは、オブジェクトストアのパフォーマンスに関するトラブルシューティングは行いません。
* *データ破損または損失に対する責任の免責*：NetAppは、サードパーティのS3オブジェクトストアの問題によって発生したデータ損失やサービス停止については、一切責任を負いません。
* *限定的な機能サポート*：サードパーティの S3 互換ターゲットでサポートされている機能セットは、ネイティブターゲット（AWS S3、Azure Blob、GCP、ONTAP S3、StorageGRID）で使用可能な機能のサブセットです。




[[prepare-your-console-agent]]
== コンソールエージェントを準備する

コンソール エージェントは、コンソール機能のメイン ソフトウェアです。  ONTAPデータをバックアップおよび復元するには、コンソール エージェントが必要です。



[[create-or-switch-console-agents]]
=== コンソールエージェントの作成または切り替え

S3互換ストレージにデータをバックアップする場合、コンソールエージェントがオンプレミスまたはクラウド上に用意されている必要があります。新しいコンソールエージェントをインストールするか、現在選択されているコンソールエージェントが以下のいずれかの場所に存在することを確認する必要があります。オンプレミスのコンソールエージェントは、インターネット接続の有無にかかわらず、サイトにインストールできます。

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["コンソールエージェントについて学ぶ"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["クラウド環境にコンソールエージェントをインストールする"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["インターネットにアクセスできる Linux ホストにコンソール エージェントをインストールする"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["インターネットにアクセスできない Linux ホストにコンソール エージェントをインストールする"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["コンソールエージェント間の切り替え"^]




[[prepare-console-agent-networking-requirements]]
=== コンソールエージェントのネットワーク要件を準備する

コンソール エージェントがインストールされているネットワークで次の接続が有効になっていることを確認します。

* S3互換サーバーへのポート443経由のHTTPS接続
* ソースONTAPクラスタ管理 LIF へのポート 443 経由の HTTPS 接続
* NetApp Backup and Recoveryへのポート 443 経由のアウトバウンド インターネット接続 (コンソール エージェントが「ダーク」サイトにインストールされている場合は必要ありません)




==== プライベートモード（ダークサイト）の考慮事項

NetApp Backup and Recovery機能は、コンソール エージェントに組み込まれています。プライベート モードでインストールされている場合、新しい機能にアクセスするには、コンソール エージェント ソフトウェアを定期的に更新する必要があります。チェックしてくださいlink:whats-new.html["NetApp Backup and Recoveryの新機能"]NetApp Backup and Recovery の各リリースの新機能を確認してください。新しい機能を使用する場合は、次の手順に従ってください。 https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["コンソールエージェントソフトウェアをアップグレードする"^] 。

標準的なSaaS環境でNetApp Backup and Recoveryを使用する場合、NetApp Backup and Recoveryの設定データはクラウドにバックアップされます。インターネットにアクセスできないサイトでNetApp Backup and Recoveryを使用する場合、NetApp Backup and Recoveryの設定データは、バックアップが保存されているS3互換バケットにバックアップされます。



[[verify-license-requirements]]
== ライセンス要件を確認する

クラスターに対してNetApp Backup and Recoveryをアクティブ化する前に、 NetAppからNetApp Backup and Recovery BYOL ライセンスを購入してアクティブ化する必要があります。このライセンスはオブジェクト ストレージへのバックアップと復元用です。スナップショットや複製されたボリュームを作成するのにライセンスは必要ありません。このライセンスはアカウント用であり、複数のシステムで使用できます。

ライセンスの有効期間と容量にわたってサービスを使用するには、 NetAppからのシリアル番号が必要になります。link:br-start-licensing.html["BYOLライセンスの管理方法を学ぶ"]。


TIP: S3互換ストレージへのファイルバックアップ時には、PAYGOライセンスはサポートされていません。



[[prepare-your-ontap-clusters]]
== ONTAPクラスタを準備する

ソースのオンプレミスONTAPシステムと、セカンダリのオンプレミスONTAPまたはCloud Volumes ONTAPシステムを準備します。

ONTAPクラスタを準備するには、次の手順を実行します。

* NetApp ConsoleでONTAPシステムを検出する
* ONTAPのシステム要件を確認する
* オブジェクトストレージにデータをバックアップするためのONTAPネットワーク要件を確認する
* ボリュームを複製するためのONTAPネットワーク要件を確認する




[[discover-your-ontap-systems-in-netapp-console]]
=== NetApp ConsoleでONTAPシステムを検出する

ソースのオンプレミスONTAPシステムとセカンダリのオンプレミスONTAPまたはCloud Volumes ONTAPシステムの両方が、 NetApp Consoleの*システム* ページで利用できる必要があります。

クラスターを追加するには、クラスター管理 IP アドレスと管理者ユーザー アカウントのパスワードを知っておく必要があります。https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["クラスターの検出方法を学ぶ"^]。



[[verify-ontap-system-requirements]]
=== ONTAPのシステム要件を確認する

ONTAPシステムが次の要件を満たしていることを確認してください。

* 最低でもONTAP 9.8、 ONTAP 9.8P13 以降が推奨されます。
* SnapMirrorライセンス (プレミアム バンドルまたはデータ保護バンドルの一部として含まれています)。
+
*注:* NetApp Backup and Recoveryを使用する場合、「Hybrid Cloud Bundle」は必要ありません。

+
方法を学ぶ https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["クラスターライセンスを管理する"^]。

* 時間とタイムゾーンは正しく設定されています。方法を学ぶ https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["クラスター時間を設定する"^]。
* データを複製する場合は、ソース システムと宛先システムで互換性のあるONTAPバージョンが実行されていることを確認します。
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror関係に互換性のあるONTAPバージョンを表示する"^]。





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== オブジェクトストレージにデータをバックアップするためのONTAPネットワーク要件を確認する

オブジェクト ストレージに接続するシステムでは、次の要件が満たされていることを確認する必要があります。

[NOTE]
====
* ファンアウト バックアップ アーキテクチャを使用する場合は、プライマリ ストレージ システムで設定を構成する必要があります。
* カスケード バックアップ アーキテクチャを使用する場合は、セカンダリ ストレージ システムで設定を構成する必要があります。
+
link:prev-ontap-protect-journey.html["バックアップアーキテクチャの種類について詳しく学ぶ"]。



====
次のONTAPクラスタ ネットワーク要件が必要です。

* ONTAP クラスターは、バックアップおよびリストア操作のために、クラスター間 LIF から S3 互換サーバーへのユーザー指定ポートを介した HTTPS 接続を開始します。ポートはバックアップのセットアップ時に設定できます。
+
ONTAP はオブジェクト ストレージとの間でデータの読み取りと書き込みを行います。オブジェクト ストレージは開始することはなく、応答するだけです。

* ONTAP、コンソール エージェントからクラスタ管理 LIF への着信接続が必要です。
* バックアップするボリュームをホストする各ONTAPノードには、クラスタ間 LIF が必要です。  LIF は、 ONTAP がオブジェクト ストレージに接続するために使用する _IPspace_ に関連付ける必要があります。 https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["IPspacesについて詳しくはこちら"^] 。
+
NetApp Backup and Recoveryをセットアップするときに、使用する IPspace の入力を求められます。各 LIF が関連付けられている IPspace を選択する必要があります。これは、「デフォルト」の IPspace の場合もあれば、作成したカスタム IPspace の場合もあります。

* ノードのクラスタ間 LIF はオブジェクト ストアにアクセスできます (コンソール エージェントが「ダーク」サイトにインストールされている場合は必要ありません)。
* ボリュームが配置されているストレージ VM に対して DNS サーバーが構成されています。方法を見る https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["SVMのDNSサービスを構成する"^]。
* デフォルト以外のIPspaceを使用している場合は、オブジェクトストレージにアクセスするための静的ルートの作成が必要になることがあります。
* 必要に応じてファイアウォール ルールを更新し、指定したポート (通常はポート 443) を介してONTAPからオブジェクト ストレージへのNetApp Backup and Recoveryサービス接続と、ポート 53 (TCP/UDP) を介してストレージ VM から DNS サーバーへの名前解決トラフィックを許可します。




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== ボリュームを複製するためのONTAPネットワーク要件を確認する

NetApp Backup and Recoveryを使用してセカンダリONTAPシステムに複製ボリュームを作成する場合は、ソース システムと宛先システムが次のネットワーク要件を満たしていることを確認してください。

* クラスターがオンプレミスにある場合は、企業ネットワークからクラウド プロバイダーの仮想ネットワークへの接続が必要です。これは通常、VPN 接続です。
* ONTAPクラスタは、追加のサブネット、ポート、ファイアウォール、およびクラスタの要件を満たす必要があります。




[[activate-backups-on-your-ontap-volumes]]
== ONTAPボリューム上のバックアップをアクティブ化する

オンプレミスのシステムからいつでも直接バックアップをアクティブ化できます。

ウィザードに従って、次の主要な手順を実行します。

* バックアップしたいボリュームを選択します
* バックアップ戦略とポリシーを定義する
* 選択内容を確認する


また、<<APIコマンドを表示する>>レビュー ステップでコードをコピーして、将来のシステムのバックアップ アクティベーションを自動化できます。



[[start-the-wizard]]
=== ウィザードを起動する

.手順
. 次のいずれかの方法で、バックアップと回復のアクティブ化ウィザードにアクセスします。
+
** コンソールの *システム* ページで、システムを選択し、右側のパネルの [バックアップとリカバリ] の横にある *有効化 > バックアップ ボリューム* を選択します。
** バックアップとリカバリバーで*ボリューム*を選択します。  [ボリューム] タブで、*アクション (...)* オプションを選択し、単一のボリューム (オブジェクト ストレージへのレプリケーションまたはバックアップがまだ有効になっていない) に対して *バックアップのアクティブ化* を選択します。


+
ウィザードの「概要」ページには、ローカル スナップショット、レプリケーション、バックアップなどの保護オプションが表示されます。この手順で 2 番目のオプションを実行した場合、ボリュームが 1 つ選択された状態で「バックアップ戦略の定義」ページが表示されます。

. 次のオプションを続行します。
+
** コンソールエージェントがすでにある場合は、設定は完了です。  *次へ*を選択してください。
** コンソール エージェントがない場合は、[*コンソール エージェントの追加*] オプションが表示されます。参照<<コンソールエージェントを準備する>>。






[[select-the-volumes-that-you-want-to-back-up]]
=== バックアップしたいボリュームを選択します

保護するボリュームを選択します。保護されたボリュームとは、スナップショット ポリシー、レプリケーション ポリシー、オブジェクトへのバックアップ ポリシーの 1 つ以上を持つボリュームです。

FlexVolまたはFlexGroupボリュームを保護することを選択できますが、システムのバックアップをアクティブ化するときにこれらのボリュームを混在して選択することはできません。方法を見るlink:prev-ontap-backup-manage.html["システム内の追加ボリュームのバックアップを有効にする"](FlexVolまたはFlexGroup) 初期ボリュームのバックアップを構成した後。

[NOTE]
====
* 一度に 1 つのFlexGroupボリューム上でのみバックアップをアクティブ化できます。
* 保護するソースボリュームを選択する際は、一致するSnapLock設定を持つボリュームのみを選択できます。選択するボリュームは、すべてSnapLock機能が有効になっているか、すべてSnapLock機能が無効になっている必要があります。


====
.手順
選択したボリュームにすでにスナップショットまたはレプリケーション ポリシーが適用されている場合は、後で選択したポリシーによって既存のポリシーが上書きされることに注意してください。

. 「ボリュームの選択」ページで、保護するボリュームを選択します。
+
** 必要に応じて、行をフィルタリングして、特定のボリューム タイプ、スタイルなどを持つボリュームのみを表示し、選択を容易にします。
** 最初のボリュームを選択したら、すべてのFlexVolボリュームを選択できます (FlexGroupボリュームは一度に 1 つだけ選択できます)。既存のFlexVolボリュームをすべてバックアップするには、まず 1 つのボリュームをチェックし、次にタイトル行のボックスをチェックします。
** 個々のボリュームをバックアップするには、各ボリュームのボックスをオンにします。


. *次へ*を選択します。




[[define-the-backup-strategy]]
=== バックアップ戦略を定義する

バックアップ戦略を定義するには、次のオプションを構成する必要があります。

* 保護オプション: ローカルスナップショット、レプリケーション、オブジェクトストレージへのバックアップなど、バックアップオプションの1つまたはすべてを実装するかどうか
* アーキテクチャ: ファンアウトまたはカスケードバックアップアーキテクチャを使用するかどうか
* ローカルスナップショットポリシー
* レプリケーションターゲットとポリシー
* オブジェクト ストレージ情報へのバックアップ (プロバイダー、暗号化、ネットワーク、バックアップ ポリシー、エクスポート オプション)。


.手順
. 「バックアップ戦略の定義」ページで、次のいずれかまたはすべてを選択します。デフォルトでは 3 つすべてが選択されています。
+
** *ローカル スナップショット*: ローカル スナップショットを作成します。
** *レプリケーション*: 別のONTAPストレージ システムに複製されたボリュームを作成します。
** *バックアップ*: S3 用に設定されたONTAPシステム上のバケットにボリュームをバックアップします。


. *アーキテクチャ*: レプリケーションとバックアップの両方を選択した場合は、次のいずれかの情報フローを選択します。
+
** *カスケード*: バックアップ データはプライマリ システムからセカンダリ システムへ流れ、次にセカンダリ システムからオブジェクト ストレージへ流れます。
** *ファンアウト*: バックアップ データはプライマリ システムからセカンダリ システムへ、そしてプライマリ システムからオブジェクト ストレージへ流れます。
+
これらのアーキテクチャの詳細については、link:prev-ontap-protect-journey.html["保護の旅を計画する"] 。



. *ローカル スナップショット*: 既存のスナップショット ポリシーを選択するか、新しいポリシーを作成します。
+

TIP: スナップショットをアクティブ化する前にカスタムポリシーを作成する場合は、System ManagerまたはONTAP CLIを使用できます。 `snapmirror policy create`指示。参照。

+

TIP: バックアップとリカバリを使用してカスタムポリシーを作成するには、link:br-use-policies-create.html["ポリシーを作成します。"] 。

+
ポリシーを作成するには、[*新しいポリシーの作成*] を選択し、次の操作を行います。

+
** ポリシーの名前を入力します。
** 通常は異なる頻度のスケジュールを最大 5 つ選択します。
** *作成*を選択します。


. *レプリケーション*: *レプリケーション* を選択した場合は、次のオプションを設定します。
+
** *レプリケーション対象*：宛先システムとストレージVMを選択します。必要に応じて、宛先アグリゲート（FlexGroupボリュームの場合は複数のアグリゲート）と、レプリケートされたボリューム名に追加されるプレフィックスまたはサフィックスを選択します。
** *レプリケーション ポリシー*: 既存のレプリケーション ポリシーを選択するか、新しいポリシーを作成します。
+
ポリシーを作成するには、[*新しいポリシーの作成*] を選択し、次の操作を行います。

+
*** ポリシーの名前を入力します。
*** 通常は異なる頻度のスケジュールを最大 5 つ選択します。
*** *作成*を選択します。




. *オブジェクトにバックアップ*: *バックアップ*を選択した場合は、次のオプションを設定します。
+
** *プロバイダー*: * ONTAP S3* を選択します。
** *プロバイダー設定*: S3 サーバーの FQDN の詳細、ポート、ユーザーのアクセス キーとシークレット キーを入力します。
+
アクセス キーとシークレット キーは、作成したユーザーがONTAPクラスターに S3 バケットへのアクセス権を付与するためのものです。

** *ネットワーク*: バックアップするボリュームが存在するソースONTAPクラスタ内の IPspace を選択します。この IPspace のクラスタ間 LIF には、アウトバウンド インターネット アクセスが必要です (コンソール エージェントが「ダーク」サイトにインストールされている場合は必要ありません)。
+

TIP: 正しい IPspace を選択すると、 NetApp Backup and Recovery がONTAPからONTAP S3 オブジェクト ストレージへの接続を確立できるようになります。

** *バックアップ ポリシー*: 既存のバックアップ ポリシーを選択するか、新しいバックアップ ポリシーを作成します。
+

TIP: System Manager またはONTAP CLI を使用してポリシーを作成できます。  ONTAP CLIを使用してカスタムポリシーを作成するには `snapmirror policy create`コマンドについては、 。

+

TIP: バックアップとリカバリを使用してカスタムポリシーを作成するには、link:br-use-policies-create.html["ポリシーを作成します。"] 。

+
ポリシーを作成するには、[*新しいポリシーの作成*] を選択し、次の操作を行います。

+
*** ポリシーの名前を入力します。
*** 通常は異なる頻度のスケジュールを最大 5 つ選択します。
*** オブジェクトへのバックアップ ポリシーについては、Datalock とランサムウェアの保護設定を行います。Datalock とランサムウェア対策の詳細については、link:prev-ontap-policy-object-options.html["オブジェクトへのバックアップポリシー設定"]を参照してください。
*** *作成*を選択します。


** *既存のスナップショットをバックアップ ファイルとしてオブジェクト ストレージにエクスポートする*: このシステム内のボリュームに、選択したバックアップ スケジュール ラベル (たとえば、毎日、毎週など) に一致するローカル スナップショットがある場合は、この追加プロンプトが表示されます。このボックスをオンにすると、すべての履歴スナップショットがバックアップ ファイルとしてオブジェクト ストレージにコピーされ、ボリュームの最も完全な保護が確保されます。


. *次へ*を選択します。




[[review-your-selections]]
=== 選択内容を確認する

ここで選択内容を確認し、必要に応じて調整を行うことができます。

.手順
. 「レビュー」ページで選択内容を確認します。
. オプションで、*スナップショット ポリシー ラベルをレプリケーション ポリシー ラベルおよびバックアップ ポリシー ラベルと自動的に同期する* チェックボックスをオンにします。これにより、レプリケーションおよびバックアップ ポリシーのラベルと一致するラベルを持つスナップショットが作成されます。ポリシーが一致しない場合、バックアップは作成されません。
. *バックアップの有効化*を選択します。


.結果
NetApp Backup and Recovery はボリュームの初期バックアップを開始します。複製されたボリュームとバックアップ ファイルのベースライン転送には、ソース データの完全なコピーが含まれます。後続の転送には、スナップショットに含まれるプライマリ ストレージ データの差分コピーが含まれます。

複製されたボリュームが宛先クラスターに作成され、プライマリ ストレージ ボリュームと同期されます。

入力した S3 アクセスキーとシークレットキーで示されるサービスアカウントに S3 バケットが作成され、そこにバックアップファイルが保存されます。

ボリューム バックアップ ダッシュボードが表示され、バックアップの状態を監視できます。

バックアップと復元ジョブのステータスを監視することもできます。link:br-use-monitor-tasks.html["ジョブ監視ページ"] 。



[[show-the-api-commands]]
=== APIコマンドを表示する

バックアップとリカバリのアクティブ化ウィザードで使用される API コマンドを表示し、必要に応じてコピーすることもできます。将来のシステムでバックアップのアクティベーションを自動化するには、これを実行する必要がある場合があります。

.手順
. バックアップとリカバリのアクティブ化ウィザードから、*API リクエストの表示*を選択します。
. コマンドをクリップボードにコピーするには、[コピー] アイコンを選択します。

