---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery は、 1 つの Google アーカイブ ストレージ クラスとほとんどのリージョンをサポートしています。 
---
= NetApp Backup and Recoveryでサポートされている Google アーカイブ ストレージ層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery は、 1 つの Google アーカイブ ストレージ クラスとほとんどのリージョンをサポートしています。

[]
====

NOTE: NetApp Backup and Recovery UIのバージョンを切り替えるには、link:br-start-switch-ui.html["以前のNetApp Backup and RecoveryUIに切り替える"] 。

====


== NetApp Backup and Recoveryでサポートされている Google アーカイブ ストレージ クラス

バックアップ ファイルは、最初に作成されると、_標準_ ストレージに保存されます。この層は、アクセス頻度の低いデータを保存するように最適化されていますが、すぐにアクセスすることもできます。

オンプレミスのクラスターでONTAP 9.12.1 以降を使用している場合は、一定の日数 (通常は 30 日以上) が経過すると、 NetApp Backup and Recovery UI で古いバックアップをアーカイブ ストレージに階層化して、コストをさらに最適化することができます。この層のデータは取得コストが高くなるため、アーカイブされたバックアップ ファイルからデータを復元する必要がある頻度を考慮する必要があります。アーカイブ ストレージからのデータの復元については、このページのセクションを参照してください。

このタイプのライフサイクル ルールを使用してNetApp Backup and Recoveryを構成する場合は、Google アカウントでバケットを設定するときにライフサイクル ルールを構成しないでください。

https://cloud.google.com/storage/docs/storage-classes["Google のストレージ クラスについて学ぶ"^]。



== アーカイブストレージからデータを復元する

古いバックアップ ファイルをアーカイブ ストレージに保存すると、標準ストレージよりもはるかに安価になりますが、復元操作のためにアーカイブ ストレージのバックアップ ファイルからデータにアクセスすると、少し時間がかかり、コストも高くなります。

Google アーカイブからデータを復元するにはいくらかかりますか?:: Google Cloud Storageの地域別の料金の詳細については、 https://cloud.google.com/storage/pricing["Google Cloud Storage の料金ページ"^] 。
Google アーカイブにアーカイブされたオブジェクトの復元にはどのくらいの時間がかかりますか?:: 復元時間全体は 2 つの部分で構成されます。
+
--
* *取得時間*: アーカイブからバックアップ ファイルを取得して標準ストレージに配置する時間。これは「再水和」時間と呼ばれることもあります。他のクラウド プロバイダーが提供する「最も冷たい」ストレージ ソリューションとは異なり、データには数ミリ秒以内にアクセスできます。
* *復元時間*: 標準ストレージ内のバックアップ ファイルからデータを復元する時間。この時間は、アーカイブ層を使用しない場合に、標準ストレージから直接実行する一般的な復元操作と変わりません。


--

