---
settings:
  name: NetApp Backup and Recovery
  release_notes_autogen:
    release_notes_repo: console-local-relnotes, console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp Backup and Recoveryのドキュメント
    url: "/index.html"
  - title: リリース ノート
    entries:
    - title: NetApp Backup and Recoveryの新機能
      url: "/whats-new.html"
    - title: ONTAPボリュームワークロードの既知の制限
      url: "/br-reference-limitations.html"
    - title: SQL Serverワークロードに関する既知の制限事項
      url: "/br-limitations.html"
    - title: VMware ワークロードの既知の制限
      url: "/br-limitations-vmware.html"
    - title: Hyper-V ワークロードの既知の制限
      url: "/br-limitations-hyperv.html"
    - title: KVMワークロードの既知の制限
      url: "/br-limitations-kvm.html"
    - title: Oracle Databaseワークロードの既知の制限
      url: "/br-limitations-oracle.html"
  - title: 始めましょう
    entries:
    - title: NetApp Backup and Recoveryについて学ぶ
      url: "/concept-backup-to-cloud.html"
    - title: NetApp Backup and Recoveryの要件
      url: "/concept-start-prereq.html"
    - title: ライセンスの設定
      url: "/br-start-licensing.html"
    - title: セキュリティ証明書を設定する
      url: "/task-setup-ca-certificates.html"
    - title: NetApp Backup and Recoveryを使用する前にバックアップ先を設定する
      url: "/br-start-setup.html"
    - title: オフサイトバックアップターゲットの検出
      url: "/br-start-discover-backup-targets.html"
    - title: さまざまなNetApp Backup and Recoveryワークロードに切り替える
      url: "/br-start-switch-ui.html"
    - title: NetApp Backup and Recovery設定を構成する
      url: "/br-start-configure.html"
    - title: ロールベースアクセス制御の設定
      url: "/br-rbac-setup.html"
  - title: NetApp Backup and Recoveryを使用する
    entries:
    - title: NetApp Backup and Recoveryにログイン
      url: "/br-start-login.html"
    - title: NetApp Backup and Recoveryダッシュボードで保護の健全性を確認する
      url: "/br-use-dashboard.html"
    - title: ONTAPボリュームのワークロードを保護する
      entries:
      - title: NetApp Backup and Recovery for ONTAP ボリュームについて
        url: "/prev-ontap-protect-overview.html"
      - title: NetApp Backup and Recovery を有効にしてボリュームを保護する
        url: "/br-start-enable.html"
      - title: NetApp Backup and Recovery のローカル展開における検索とリストアのパフォーマンスの向上
        url: "/prev-ontap-protect-migrate-pvc.html"
      - title: NetApp Backup and Recoveryの保護ジャーニー計画オプション
        url: "/prev-ontap-protect-journey.html"
      - title: アクティベーションなしで ONTAP システムとボリュームを検出する
        url: "/prev-ontap-discover-no-activate.html"
      - title: ONTAP ボリュームのバックアップポリシーを管理する
        url: "/prev-ontap-policy-manage.html"
      - title: ONTAPボリュームのオブジェクトへのバックアップポリシーオプション
        url: "/prev-ontap-policy-object-options.html"
      - title: オブジェクトストレージへのバックアップオプションを管理する
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Cloud Volumes ONTAPデータを Amazon S3 にバックアップする
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Cloud Volumes ONTAP データを Azure Blob ストレージにバックアップする
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Cloud Volumes ONTAP データを Google Cloud Storage にバックアップする
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: オンプレミスのONTAPデータを Amazon S3 にバックアップする
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: オンプレミスの ONTAP データを Azure Blob ストレージにバックアップする
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: オンプレミスの ONTAP データを Google Cloud Storage にバックアップする
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: オンプレミスのONTAPデータをONTAP S3 にバックアップする
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: オンプレミス ONTAP データを S3 互換ストレージにバックアップする
        url: "/prev-ontap-backup-onprem-s3-compatible.html"
      - title: オンプレミスのONTAPデータをStorageGRIDにバックアップする
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: SnapMirror を使用して ONTAP ボリュームをクラウドに移行して再同期する
        url: "/prev-ontap-migrate-resync.html"
      - title: ONTAPシステムのバックアップを管理する
        url: "/prev-ontap-backup-manage.html"
      - title: ONTAPバックアップからの復元
        entries:
        - title: ONTAP データのリストアオプション
          url: "/prev-ontap-restore.html"
        - title: 検索とリストアを使用したONTAPデータのリストア
          url: "/prev-ontap-restore-search.html"
        - title: Browse and Restore を使用して ONTAP データをリストアする
          url: "/prev-ontap-restore-browse.html"
    - title: Microsoft SQL Server ワークロードを保護する
      entries:
      - title: Microsoft SQL Server の保護ワークフロー（NetApp Backup and Recovery）
        url: "/br-use-mssql-protect-overview.html"
      - title: SnapCenter の NetApp Backup and Recovery へのインポートの前提条件
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Microsoft SQL Server ワークロードの検出
        url: "/br-start-discover.html"
      - title: Microsoft SQL Server バックアップポリシーの作成と管理
        url: "/br-use-policies-mssql-create.html"
      - title: Microsoft SQL Server ワークロードのバックアップ
        url: "/br-use-mssql-backup.html"
      - title: Microsoft SQL Server ワークロードを復元する
        url: "/br-use-mssql-restore.html"
      - title: Microsoft SQL Server ワークロードのクローン作成
        url: "/br-use-mssql-clone.html"
      - title: Microsoft SQL Server のインベントリを管理する
        url: "/br-use-manage-inventory.html"
      - title: Microsoft SQL Server スナップショットを管理する
        url: "/br-use-manage-snapshots.html"
      - title: Microsoft SQL Server レポートを作成する
        url: "/br-use-reports.html"
    - title: VMwareワークロードを保護する
      entries:
      - title: VMware保護ワークフロー
        url: "/br-use-vmware-protect-overview.html"
      - title: VMware ワークロードを発見
        url: "/br-use-vmware-discovery.html"
      - title: VMware保護グループを管理する
        url: "/br-use-vmware-protection-groups.html"
      - title: VMwareバックアップポリシーの管理
        url: "/br-use-policies-vmware-create.html"
      - title: VMwareワークロードのバックアップ
        url: "/br-use-vmware-backup.html"
      - title: VMwareワークロードをクローンする
        url: "/br-use-vmware-clone.html"
      - title: VMwareワークロードを復元する
        entries:
        - title: VMwareワークロードを復元する
          url: "/br-use-vmware-restore.html"
        - title: VMware仮想ディスクをバックアップからリストアする
          url: "/br-use-vmware-restore-vmdks-from-backups.html"
        - title: VMwareのファイルとフォルダをリストアする
          entries:
          - title: VMwareゲストファイルのリストア要件
            url: "/br-use-vmware-restore-guest-files-and-folders-overview.html"
          - title: VMwareゲストのファイルとフォルダのリストア
            url: "/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html"
          - title: ファイルとフォルダのリストアのトラブルシューティング
            url: "/br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html"
    - title: KVMワークロードを保護する
      entries:
      - title: KVM ワークロードの保護の概要
        url: "/br-use-kvm-protect-overview.html"
      - title: KVMワークロードを発見
        url: "/br-start-discover-kvm.html"
      - title: KVM ワークロードの保護グループの作成と管理
        url: "/br-use-kvm-protection-groups.html"
      - title: KVMワークロードのバックアップポリシーを作成および管理する
        url: "/br-use-policies-kvm-create.html"
      - title: KVMワークロードのバックアップ
        url: "/br-use-kvm-backup.html"
      - title: KVMワークロードを復元する
        url: "/br-use-kvm-restore.html"
    - title: Hyper-V ワークロードを保護する
      entries:
      - title: Hyper-V ワークロードの保護の概要
        url: "/br-use-hyperv-protect-overview.html"
      - title: Hyper-V ワークロードの検出
        url: "/br-start-discover-hyperv.html"
      - title: Hyper-V ワークロードの保護グループの作成と管理
        url: "/br-use-hyperv-protection-groups.html"
      - title: Hyper-Vワークロードのバックアップポリシーを作成および管理する
        url: "/br-use-policies-hyper-v-create.html"
      - title: Hyper-V ワークロードのバックアップ
        url: "/br-use-hyperv-backup.html"
      - title: Hyper-V ワークロードを復元する
        entries:
        - title: Hyper-V ワークロードを復元する
          url: "/br-use-hyperv-restore.html"
        - title: Hyper-Vのファイルとフォルダをリストアする
          url: "/br-use-hyper-v-restore-guest-files-and-folders.html"
    - title: Oracle Database ワークロードの保護（プレビュー）
      entries:
      - title: Oracle Databaseワークロードの保護の概要
        url: "/br-use-oracle-protect-overview.html"
      - title: Oracle Databaseワークロードを検出
        url: "/br-start-discover-oracle.html"
      - title: Oracleデータベースを設定する
        url: "/br-start-configure-oracle-database.html"
      - title: Oracle Database ワークロードの保護グループの作成と管理
        url: "/br-use-oracle-protection-groups.html"
      - title: Oracle Databaseワークロードのバックアップポリシーを作成および管理する
        url: "/br-use-policies-oracle-create.html"
      - title: Oracle Databaseワークロードのバックアップ
        url: "/br-use-oracle-backup.html"
      - title: Oracle Database ワークロードのクローン作成
        url: "/br-use-oracle-clone.html"
      - title: Oracle Database ワークロードのリストア
        url: "/br-use-oracle-restore.html"
      - title: リカバリ ポイントのマウント、アンマウント、およびカタログ化
        url: "/br-use-oracle-mount-unmount.html"
    - title: Kubernetesワークロードを保護する
      entries:
      - title: Kubernetes ワークロードの保護の概要
        url: "/br-use-kubernetes-protect-overview.html"
      - title: Kubernetes ワークロードを発見する
        url: "/br-start-discover-kubernetes.html"
      - title: Kubernetes アプリケーションの追加と保護
        entries:
        - title: Kubernetes アプリケーションの追加と保護
          url: "/br-use-protect-kubernetes-applications.html"
        - title: Kubernetesワークロードのバックアップポリシーを作成および管理する
          url: "/br-use-policies-kubernetes-create.html"
        - title: Web UI を使用して Kubernetes アプリケーションを今すぐバックアップする
          url: "/br-use-back-up-now-kubernetes-applications-web-ui.html"
        - title: カスタムリソースを使用してKubernetesアプリケーションを今すぐバックアップ
          url: "/br-use-back-up-now-kubernetes-applications-cr.html"
      - title: Kubernetesアプリケーションを復元する
        entries:
        - title: Web UI を使用して Kubernetes アプリケーションをリストアする
          url: "/br-use-restore-kubernetes-applications.html"
        - title: カスタムリソースを使用してKubernetesアプリケーションを復元する
          url: "/br-use-restore-kubernetes-applications-cr.html"
        - title: 高度なカスタムリソースのリストア設定を使用する
          url: "/br-use-kubernetes-advanced-restore-settings.html"
        - title: カスタムリソースを使用して復元操作中にリソースを変更する
          url: "/br-use-modify-resources-kubernetes-cr.html"
      - title: Kubernetes クラスターを管理する
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: Kubernetes アプリケーションを管理する
        url: "/br-use-manage-kubernetes-applications.html"
      - title: Kubernetes ワークロードの実行フック テンプレートを管理する
        url: "/br-use-manage-execution-hook-templates.html"
      - title: 保護レポートの作成と管理
        url: "/br-use-kubernetes-reports.html"
    - title: ジョブの監視
      url: "/br-use-monitor-tasks.html"
    - title: NetApp Backup and Recoveryを再起動します
      url: "/reference-restart-backup.html"
    - title: プレビューと隠し機能を有効にする
      url: "/enable-preview-features.html"
  - title: NetApp Backup and RecoveryREST API による自動化
    url: "/br-api-backup-restore.html"
  - title: 参照
    entries:
    - title: 監査済み NetApp Backup and Recovery アクション
      url: "/reference-audit-actions.html"
    - title: SnapCenterのポリシーとNetApp Backup and Recovery のポリシーの比較
      url: "/reference-policy-differences-snapcenter.html"
    - title: NetApp Backup and Recovery IAM ロール
      url: "/reference-roles.html"
    - title: ダークサイトでのNetApp Backup and Recovery構成データの復元
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: NetApp Backup and Recoveryでサポートされている AWS アーカイブ ストレージ層
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: サポートされている Azure アーカイブストレージティアと NetApp Backup and Recovery
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Google Cloud アーカイブストレージ階層のサポート（NetApp Backup and Recovery）
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: 法律上の表示
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
