---
sidebar: sidebar 
permalink: reference-policy-differences-snapcenter.html 
keywords: backup policy, backup policies, snapcenter, migration 
summary: NetApp Backup and Recovery で使用されるポリシーとSnapCenterで使用されるポリシーにはいくつかの違いがあります。 
---
= SnapCenterのポリシーとNetApp Backup and Recovery のポリシーの比較
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapCenterで使用されるポリシーとNetApp Backup and Recovery で使用されるポリシーにはいくつかの違いがあり、 SnapCenterからリソースとポリシーをインポートした後の表示内容に影響する可能性があります。



== スケジュール階層

SnapCenter は次のスケジュール層を使用します。

* *時間単位*: 任意の時間 (0 ～ 23) と任意の分 (0 ～ 60) で複数の時間と分を指定します。
* *毎日*: 3 日ごとなど、指定した日数ごとに繰り返すオプションが含まれます。
* *毎週*: 日曜日から月曜日まで。週の 1 日目にスナップショットを実行するか、週の複数の日にスナップショットを実行するかを選択できます。
* *毎月*: 1 月から 12 月までの月で、毎月 7 日など、月の特定の日に実行するオプションや、月の複数の日に実行するオプションがあります。


NetApp Backup and Recovery では、若干異なる次のスケジュール層が使用されます。

* *時間ごと*: 15 分間隔でのみスナップショットを実行します (例: 1 時間または 60 未満の 15 分間隔)。
* *毎日*: 1 日の時間帯 (0 ～ 23)、開始時刻 (例: 午前 10:00)、および一定時間ごとに実行するオプション。
* *毎週*: 曜日 (日曜日から月曜日)。1 日または複数日に実行するオプションがあります。これはSnapCenterと同じです。
* *月次*: 月内の複数の日付の開始時刻を持つ日付 (0 ～ 30)。
* *年間*: 月単位。これは SnapCenter の月次と一致します。




== SnapCenterで同じスケジュール層を持つ複数のポリシー

SnapCenterのリソースに、同じスケジュール層を持つ複数のポリシーを割り当てることができます。ただし、 NetApp Backup and Recovery では、同じスケジュール層を使用するリソース上の複数のポリシーはサポートされていません。

*例*: SnapCenterで 3 つのポリシー (データ、ログ、スナップショットのログ) を使用している場合、 SnapCenterからの移行後、 NetApp Backup and Recovery は 3 つすべてのポリシーではなく 1 つのポリシーを使用します。



== インポートされたSnapCenterの毎日のスケジュール

NetApp Backup and Recovery は、 SnapCenter のスケジュールを次のように調整します。

* SnapCenter のスケジュールが 7 日以下に設定されている場合、 NetApp Backup and Recovery はスケジュールを毎週に設定します。週中、一部のスナップショットはスキップされます。
+
*例*: 月曜日から始まり 3 日ごとに繰り返す間隔を持つSnapCenter の日次ポリシーがある場合、 NetApp Backup and Recovery は月曜日、木曜日、日曜日にスケジュールを毎週設定します。正確に 3 日ごとではないため、一部の日がスキップされます。

* SnapCenter のスケジュールが 7 日以上に設定されている場合、 NetApp Backup and Recovery はスケジュールを月単位に設定します。月中は一部のスナップショットがスキップされます。
+
*例*: 毎月 2 日から 10 日ごとに繰り返す間隔を持つSnapCenter の日次ポリシーがある場合、 NetApp Backup and Recovery (移行後) は、毎月 2 日、12 日、22 日にスケジュールを毎月に設定します。翌月は何日かスキップされます。





== インポートされたSnapCenterの時間別スケジュール

繰り返し間隔が 1 時間を超えるSnapCenter の時間別ポリシーは、 NetApp Backup and Recovery の日次ポリシーに変換されます。

繰り返し間隔が 24 の倍数ではない (たとえば 5、7 など) 時間単位のポリシーでは、1 日にいくつかのスナップショットがスキップされます。

*例*: 午前 1 時から 5 時間ごとに繰り返す間隔を持つSnapCenter の時間単位ポリシーがある場合、 NetApp Backup and Recovery (移行後) は、午前 1 時、午前 6 時、午前 11 時、午後 4 時、午後 9 時の 5 時間間隔で毎日スケジュールを設定します。いくつかの時間はスキップされます。午後 9:00 以降は 5 時間ごとに繰り返すために午前 2:00 になるはずですが、常に午前 1:00 になります。



== SnapCenterポリシーからのログ保持

SnapCenterに複数のポリシーを持つリソースがある場合、 NetApp Backup and Recovery は次の優先順位を使用してログ保持値を割り当てます。

* SnapCenterの「ログ バックアップ ポリシーによる完全バックアップ」と「ログのみ」ポリシーの場合、 NetApp Backup and Recovery はログのみポリシーの保持値を使用します。
* SnapCenterの「ログのみの完全バックアップ」および「完全バックアップとログ」ポリシーの場合、 NetApp Backup and Recovery はログのみの保持値を使用します。
* SnapCenterの「フル バックアップとログ」と「フル バックアップ」の場合、 NetApp Backup and Recovery は「フル バックアップとログ」の保持値を使用します。
* SnapCenterに完全バックアップのみがある場合、 NetApp Backup and Recovery ではログ バックアップは有効になりません。




== ログバックアップの保持

SnapCenter を使用すると、リソースにアタッチされた複数のポリシーにわたって複数の保持値を持つことができます。ただし、 NetApp Backup and Recovery では、リソースに添付されたすべてのポリシーに対して単一の保持値のみがサポートされます。



== SnapCenterポリシーからの保持数

SnapCenterで、複数のソース ボリューム、複数の宛先ボリューム、および複数のSnapMirror関係を持つセカンダリ保護が有効になっているリソースがある場合、 NetApp Backup and Recovery は最初のポリシーの保持数のみを使用します。

*例*: 保持数が 5 のSnapCenterポリシーと、保持数が 10 の別のポリシーがある場合、 NetApp Backup and Recovery は保持数 5 を使用します。



== SnapCenterポリシーからのSnapMirrorラベル

SnapCenterのすべてのポリシーのSnapMirrorラベルは、階層が変更されても移行後もそのまま残ります。

*例*: SnapCenterの時間単位のポリシーが、 NetApp Backup and Recovery では日単位に変更される場合があります。ただし、移行後もSnapMirrorラベルは同じままです。
