---
sidebar: sidebar 
permalink: task-preview-enable.html 
keywords: cloud backup, NetApp Backup and Recovery, backup, restore, preview, enable, object storage, third-party, MinIO, S3-compatible 
summary: ローカル スナップショット、レプリケーション、および開始またはスケジュールされたオブジェクト ストレージ ジョブへのバックアップの状態を監視したり、開始またはスケジュールされたジョブを復元したりできます。完了したジョブ、進行中のジョブ、失敗したジョブを確認して、問題を診断して修正することができます。通知センターを使用すると、電子メールによる通知の送信を有効にして、システムにログインしていないときでも重要なシステムアクティビティについて通知を受けることができます。タイムラインを使用すると、UI または API を介して開始されたすべてのアクションの詳細を確認できます。 
---
= NetAppバックアップおよびリカバリのプレビュー機能を有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery では、新しい機能が完全にリリースされる前にテストできるプレビュー機能を提供しています。これらの機能は、バックアップとリカバリのエクスペリエンスを強化するために設計されていますが、完全にサポートされておらず、安定していない可能性があります。


IMPORTANT: これらの機能はプレビュー モードであり、実稼働環境では使用しないでください。これらはテストとフィードバックのみを目的としています。



== プレビュー機能を有効にする

NetApp Backup and Recovery のプレビュー機能を有効にするには、コンソール エージェントにフラグを設定する必要があります。このフラグを使用すると、サービスで利用可能なプレビュー機能にアクセスしてテストできます。

.手順
. コンソール エージェントにログインします。
. スーパーユーザーに切り替えます。次のコマンドを実行します。
+
`sudo su`

. Docker ボリュームを一覧表示し、CBS ボリュームを識別します。次のコマンドを実行します。
+
[listing]
----
podman volume ls | grep cbs
----
+
期待される出力:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. ボリュームを検査してマウントポイントを取得します。次のコマンドを実行します。
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
. 次のコマンドを実行します。
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
期待される出力:

+
[listing]
----
Mountpoint:
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Docker Volumes ディレクトリに移動します。前の手順で取得したマウントポイントにディレクトリを変更します。
+
[listing]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config

----
. 検索して編集する `production-customer.json`ファイル。
. 正しいディレクトリにいることを確認し、 `production-customer.json`ファイルが存在します。
. 開く `production-customer.json`好みのテキスト エディターでファイルを開き、次の JSON スニペットを追加して、JSON 構造が適切に維持されるようにします。
+
[listing]
----
{
   "feature-flags":
    {
        "volumes-dashboard-v2": true
     }
}
----
. ファイルへの変更を保存します。
. NetApp Backup and Recovery Cloud Manager CBS サービスを再起動します。次のコマンドを実行します。
+
[listing]
----
podman restart cloudmanager_cbs
----

