= インデックスカタログのサポートの更新
:allow-uri-read: 




=== インデックスカタログのサポートの更新

2025 年 2 月に、データの復元における検索と復元方法で使用する更新されたインデックス作成機能 (インデックス カタログ v2) を導入しました。以前のリリースでは、オンプレミス環境でのデータ インデックス作成のパフォーマンスが大幅に向上しました。このリリースでは、インデックス カタログが Amazon Web Services、Microsoft Azure、Google Cloud Platform (GCP) 環境で利用できるようになりました。

新規のお客様の場合、すべての新しい環境では Indexed Catalog v2 がデフォルトで有効になっています。既存のお客様の場合は、環境のインデックスを再作成して、Indexed Catalog v2 を活用することができます。

.インデックスを有効にするにはどうすればいいですか?
データを復元するための検索と復元方法を使用する前に、ボリュームまたはファイルを復元する予定の各ソース作業環境で「インデックス作成」を有効にする必要があります。検索と復元を実行するときは、[*インデックスを有効にする*] オプションを選択します。

インデックスカタログはすべてのボリュームとバックアップ ファイルを追跡できるため、検索が迅速かつ効率的になります。

 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["検索と復元のインデックスを有効にする"] 。



=== Azure プライベート リンク エンドポイントとサービス エンドポイント

通常、 NetApp Backup and Recovery は、保護タスクを処理するためにクラウド プロバイダーとのプライベート エンドポイントを確立します。このリリースでは、 NetApp Backup and Recovery によるプライベート エンドポイントの自動作成を有効または無効にできるオプション設定が導入されました。プライベート エンドポイントの作成プロセスをより細かく制御したい場合、これは役立つ可能性があります。

保護を有効にするとき、または復元プロセスを開始するときに、このオプションを有効または無効にすることができます。

この設定を無効にした場合、 NetApp Backup and Recovery が適切に機能するには、プライベート エンドポイントを手動で作成する必要があります。適切な接続がないと、バックアップおよびリカバリ タスクを正常に実行できない可能性があります。



=== ONTAP S3 でのSnapMirrorからクラウドへの再同期のサポート

以前のリリースでは、 SnapMirror to Cloud Resync (SM-C Resync) のサポートが導入されました。この機能により、 NetApp環境でのボリューム移行時のデータ保護が効率化されます。このリリースでは、 ONTAP S3 の SM-C 再同期のサポートに加え、Wasabi や MinIO などの他の S3 互換プロバイダーのサポートも追加されました。



=== StorageGRID用の独自のバケットを用意する

作業環境のオブジェクト ストレージにバックアップ ファイルを作成すると、デフォルトでは、 NetApp Backup and Recovery によって、設定したオブジェクト ストレージ アカウントにバックアップ ファイル用のコンテナ (バケットまたはストレージ アカウント) が作成されます。以前は、これをオーバーライドして、Amazon S3、Azure Blob Storage、Google Cloud Storage に独自のコンテナを指定できました。このリリースでは、独自のStorageGRIDオブジェクト ストレージ コンテナーを導入できるようになりました。

見る https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-journey.html["独自のオブジェクトストレージコンテナを作成する"]。
