= 高性能インデックス
:allow-uri-read: 




=== 高性能インデックス

NetApp Backup and Recovery では、ソース システム上のデータのインデックス作成をより効率的にする、更新されたインデックス作成機能が導入されています。新しいインデックス作成機能には、UI の更新、データ復元の検索と復元方法のパフォーマンスの向上、グローバル検索機能のアップグレード、およびスケーラビリティの向上が含まれます。

改善点の内訳は次のとおりです。

* *フォルダーの統合*: 更新バージョンでは、特定の識別子を含む名前を使用してフォルダーがグループ化され、インデックス作成プロセスがスムーズになります。
* *Parquet ファイルの圧縮*: 更新バージョンでは、各ボリュームのインデックス作成に使用されるファイルの数が削減され、プロセスが簡素化され、追加のデータベースが不要になります。
* *より多くのセッションによるスケールアウト*: 新しいバージョンでは、インデックス作成タスクを処理するためのセッションが追加され、プロセスが高速化されます。
* *複数のインデックス コンテナーのサポート*: 新しいバージョンでは、複数のコンテナーを使用して、インデックス作成タスクをより適切に管理および分散します。
* *分割インデックスワークフロー*: 新しいバージョンでは、インデックス作成プロセスが 2 つの部分に分割され、効率が向上します。
* *同時実行性の向上*: 新しいバージョンでは、ディレクトリを同時に削除または移動できるようになり、インデックス作成プロセスが高速化されました。


.この機能の恩恵を受けるのは誰でしょうか?
新しいインデックス機能は、すべての新規顧客にご利用いただけます。

.インデックスを有効にするにはどうすればいいですか?
検索と復元の方法を使用してデータを復元する前に、ボリュームまたはファイルを復元する予定の各ソース システムで「インデックス作成」を有効にする必要があります。これにより、インデックス カタログですべてのボリュームとすべてのバックアップ ファイルを追跡できるようになり、検索が迅速かつ効率的になります。

検索と復元を実行するときに、「インデックスを有効にする」オプションを選択して、ソース作業環境でのインデックス作成を有効にします。

詳細については、ドキュメントを参照してください。 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["検索と復元を使用してONTAPデータを復元する方法"] 。

.サポートされているスケール
新しいインデックス機能は以下をサポートします。

* 3分以内にグローバル検索を効率化
* 最大50億ファイル
* クラスターあたり最大5000ボリューム
* ボリュームあたり最大10万個のスナップショット
* ベースライン インデックスの最大時間は 7 日未満です。実際の時間は環境によって異なります。




=== グローバル検索パフォーマンスの改善

このリリースには、グローバル検索パフォーマンスの強化も含まれています。進行状況インジケーターと、ファイルの数や検索にかかった時間などのより詳細な検索結果が表示されます。検索とインデックス作成専用のコンテナにより、グローバル検索が 5 分以内に完了します。

グローバル検索に関連する次の考慮事項に注意してください。

* 時間別としてラベル付けされたスナップショットでは、新しいインデックスは実行されません。
* 新しいインデックス機能は、FlexVol 上のスナップショットに対してのみ機能し、FlexGroup 上のスナップショットに対しては機能しません。

