= 強化されたONTAPボリュームダッシュボード
:allow-uri-read: 




=== 強化されたONTAPボリュームダッシュボード

2025 年 4 月には、はるかに高速で効率的な、強化されたONTAPボリューム ダッシュボードのプレビューをリリースしました。

このダッシュボードは、多数のワークロードを抱えるエンタープライズ顧客を支援するために設計されました。  20,000 ボリュームを持つお客様の場合でも、新しいダッシュボードは 10 秒未満で読み込まれます。

プレビューが成功し、プレビューのお客様から素晴らしいフィードバックをいただいたため、これをすべてのお客様向けのデフォルトのエクスペリエンスにすることにいたしました。驚くほど高速なダッシュボードに備えてください。

詳細については、 link:br-use-dashboard.html["ダッシュボードで保護の状態を確認する"] 。



=== パブリック テクノロジー プレビューとしての Microsoft SQL Server ワークロード サポート

NetApp Backup and Recovery のこのリリースでは、 NetApp Backup and Recovery でお馴染みの 3-2-1 保護戦略を使用して Microsoft SQL Server ワークロードを管理できる更新されたユーザー インターフェイスが提供されます。この新しいバージョンでは、これらのワークロードをプライマリ ストレージにバックアップし、セカンダリ ストレージに複製し、クラウド オブジェクト ストレージにバックアップできます。

プレビューにサインアップするには、こちらに記入してください https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["プレビュー登録フォーム"^]。


NOTE: Microsoft SQL Server ワークロードの保護に関するこのドキュメントは、テクノロジープレビューとして提供されています。このプレビュー提供において、 NetApp は一般提供開始前に提供内容、内容、およびスケジュールを変更する権利を留保します。

このバージョンのNetApp Backup and Recovery には、次の更新が含まれています。

* *3-2-1 バックアップ機能*: このバージョンではSnapCenter機能が統合されており、 NetApp Backup and Recovery ユーザー インターフェイスから 3-2-1 データ保護戦略を使用してSnapCenterリソースを管理および保護できます。
* * SnapCenterからのインポート*: SnapCenter のバックアップ データとポリシーをNetApp Backup and Recovery にインポートできます。
* *再設計されたユーザー インターフェイス* により、バックアップおよびリカバリ タスクをより直感的に管理できるようになります。
* *バックアップ ターゲット*: Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID、 ONTAP S3 環境にバケットを追加して、Microsoft SQL Server ワークロードのバックアップ ターゲットとして使用できます。
* *ワークロード サポート*: このバージョンでは、Microsoft SQL Server データベースと可用性グループのバックアップ、復元、検証、複製が可能になります。  (他のワークロードのサポートは、将来のリリースで追加される予定です。)
* *柔軟な復元オプション*: このバージョンでは、破損や偶発的なデータ損失が発生した場合に、データベースを元の場所と別の場所の両方に復元できます。
* *即時の実稼働コピー*: 開発、テスト、分析用のスペース効率の高い実稼働コピーを、数時間または数日ではなく数分で生成します。
* このバージョンには、詳細なレポートを作成する機能が含まれています。


Microsoft SQL Server ワークロードの保護の詳細については、以下を参照してください。link:br-use-mssql-protect-overview.html["Microsoft SQL Server ワークロードの保護の概要"] 。
