= UIの改善
:allow-uri-read: 




=== UIの改善

このリリースでは、インターフェースが簡素化され、エクスペリエンスが向上します。

* V2 ダッシュボードのボリューム テーブルから「集計」列が削除され、ボリューム テーブルから「スナップショット ポリシー」、「バックアップ ポリシー」、および「レプリケーション ポリシー」列が削除されたことで、レイアウトがより合理化されました。
* アクティブ化されていない作業環境をドロップダウン リストから除外すると、インターフェースが整理され、ナビゲーションが効率化され、読み込みが速くなります。
* タグ列での並べ替えが無効になっている場合でも、タグを表示できるため、重要な情報に簡単にアクセスできます。
* 保護アイコンのラベルを削除すると、見た目がすっきりし、読み込み時間が短縮されます。
* 作業環境のアクティベーション プロセス中に、ダイアログ ボックスに読み込みアイコンが表示され、検出プロセスが完了するまでフィードバックが提供されるため、システム操作の透明性と信頼性が向上します。




=== 強化されたボリュームダッシュボード（プレビュー）

ボリューム ダッシュボードは 10 秒以内に読み込まれるようになり、より高速で効率的なインターフェースが提供されます。このプレビュー バージョンは一部のお客様に提供されており、これらの改善点を早期にご確認いただけます。



=== サードパーティの Wasabi オブジェクト ストアのサポート (プレビュー)

NetApp Backup and Recovery は現在、Wasabi に重点を置き、サードパーティのオブジェクト ストアまでサポートを拡張しています。この新しいプレビュー機能により、バックアップとリカバリのニーズに合わせて、S3 互換のオブジェクト ストアを活用できるようになります。



==== Wasabiを使い始める

サードパーティのストレージをオブジェクト ストアとして使用するには、コンソール エージェント内でフラグを有効にする必要があります。次に、サードパーティのオブジェクト ストアの接続詳細を入力し、それをバックアップおよびリカバリのワークフローに統合できます。

.手順
. コネクタに SSH で接続します。
. NetApp Backup and Recovery cbs サーバー コンテナに移動します。
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 開く `default.json`ファイル内の `config`VIM または他のエディターを使用してフォルダーを開きます。
+
[listing]
----
vi default.json
----
. 修正する `allow-s3-compatible`: 偽から `allow-s3-compatible`： 真実。
. 変更を保存します。
. コンテナから出てください。
. NetApp Backup and Recovery cbs サーバー コンテナを再起動します。


.結果
コンテナが再びオンになったら、 NetApp Backup and Recovery UI を開きます。バックアップを開始するか、バックアップ戦略を編集すると、AWS、Microsoft Azure、Google Cloud、 StorageGRID、 ONTAP S3 などの他のバックアップ プロバイダーとともに、新しいプロバイダー「S3 互換」がリストされます。



==== プレビューモードの制限

この機能はプレビュー段階ですが、次の制限事項にご注意ください。

* Bring Your Own Bucket (BYOB) はサポートされていません。
* ポリシーで DataLock を有効にすることはサポートされていません。
* ポリシーでアーカイブ モードを有効にすることはサポートされていません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


このプレビュー期間中に、完全な機能が展開される前に、この新機能を確認し、サードパーティのオブジェクト ストアとの統合に関するフィードバックを提供することをお勧めします。
