= ボリューム移行のためのSnapMirrorからCloud Resyncへの変更
:allow-uri-read: 




=== ボリューム移行のためのSnapMirrorからCloud Resyncへの変更

SnapMirror to Cloud Resync 機能は、 NetApp環境でのボリューム移行中のデータ保護と継続性を合理化します。  SnapMirror Logical Replication (LRSE) を使用してボリュームをオンプレミスのNetApp展開から別の展開へ、またはCloud Volumes ONTAPやCloud Volumes Serviceなどのクラウドベースのソリューションに移行した場合、 SnapMirror to Cloud Resync により、既存のクラウド バックアップがそのまま維持され、動作可能な状態が維持されます。

この機能により、時間とリソースを大量に消費する再ベースライン操作が不要になり、移行後もバックアップ操作を続行できるようになります。この機能は、FlexVol と FlexGroup の両方をサポートし、ワークロード移行シナリオで役立ち、 ONTAPバージョン 9.16.1 以降で利用できます。

SnapMirror to Cloud Resync は、環境間でバックアップの継続性を維持することで運用効率を高め、ハイブリッドおよびマルチクラウドのデータ管理の複雑さを軽減します。

再同期操作を実行する方法の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-migrate-resync.html["SnapMirrorを使用してボリュームをCloud Resyncに移行する"] 。



=== サードパーティの MinIO オブジェクト ストアのサポート (プレビュー)

NetApp Backup and Recovery は、主に MinIO に重点を置いて、サードパーティのオブジェクト ストアまでサポートを拡張しました。この新しいプレビュー機能により、バックアップとリカバリのニーズに合わせて、S3 互換のオブジェクト ストアを活用できるようになります。

このプレビュー バージョンでは、完全な機能が展開される前に、サードパーティのオブジェクト ストアとの堅牢な統合を実現したいと考えています。ぜひこの新しい機能を試して、サービスの向上に役立つフィードバックを提供してください。


IMPORTANT: この機能は本番環境では使用しないでください。

*プレビューモードの制限*

この機能はプレビュー段階ですが、一定の制限があります。

* Bring Your Own Bucket (BYOB) はサポートされていません。
* ポリシーで DataLock を有効にすることはサポートされていません。
* ポリシーでアーカイブ モードを有効にすることはサポートされていません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


*はじめる*

このプレビュー機能の使用を開始するには、コンソール エージェントでフラグを有効にする必要があります。次に、バックアップ セクションで *サードパーティ互換* オブジェクト ストアを選択して、保護ワークフローに MinIO サードパーティ オブジェクト ストアの接続詳細を入力できます。
