= ONTAPボリュームワークロードの機能強化
:allow-uri-read: 




=== ONTAPボリュームワークロードの機能強化

このリリースのONTAPボリューム ワークロードでは、次の拡張機能が導入されています。

*複数のバケットのサポート*: (プライベート プレビュー) ONTAP 9.17.1 以降では、異なるクラウド プロバイダーにまたがるシステムごとに最大 6 つのバケットを使用して、システム内のボリュームを保護できるようになりました。

link:prev-ontap-backup-manage.html["NetApp Backup and Recoveryを使用したONTAPボリュームデータのバックアップの詳細"]。



=== VMwareワークロードの機能強化

この VMware ワークロードのリリースでは、次の拡張機能が導入されています。

* VMware ワークロード サポートが、NetApp Backup and Recovery で一般提供（GA）されました。
* ゲスト OS のファイルとフォルダーを復元できるようになりました。


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["ゲストファイルとフォルダの復元の詳細"]。



=== Hyper-V ワークロードのプレビュー機能強化

このリリースの Hyper-V ワークロードでは、次の拡張機能が導入されています。

* Hyper-V VMのバックアップとスナップショットを別の場所に復元できるようになりました。この機能を使用して、異なるHyper-Vホスト上のVMバージョンを管理できます。
* NetApp Backup and Recovery では、System Center Virtual Machine Manager（SCVMM）によってプロビジョニングされ、CIFS 共有でホストされている Hyper-V 仮想マシンがサポートされるようになりました。
* 保護グループを編集できるようになりました。



NOTE: このリリースでのみ、[アクション] メニューの [アップグレード] オプションを使用して、Hyper-V または Windows 用のNetAppプラグインをアップグレードすることはできません。代わりに、各 Hyper-V ホストを削除し、再度追加してプラグインを更新します。

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["NetApp Backup and Recoveryを使用したHyper-V VMの復元の詳細"]。



=== KVM ワークロードのプレビュー機能強化

KVM ワークロード プレビューでは、Apache CloudStack によって管理される KVM ホストと仮想マシンが保護されるようになりました。

KVMワークロードの保護の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["KVM ワークロードの保護の概要"] 。
