= ONTAPボリュームワークロードの強化
:allow-uri-read: 




[[ontap-volumes-workloads-enhancement]]
=== ONTAPボリュームワークロードの強化

今回のリリースでは、ONTAP Volumes ワークロードに、以下のプレビュー版機能強化が導入されました。

*ダークサイトのサポートを改善しました*：ダークサイト向け NetApp Backup and Recovery では、NetApp Backup and Recovery と同じ ONTAP ボリュームデータ保護機能を提供するようになりました。今回の機能強化には、バックアップ、リストア、ジョブ管理サービスの更新、および新しいメタデータデータベースが含まれています。アップグレード中は、既存のデータベースデータが保持され、自動的に移行されます。アップグレード後、監査ログを確認して、移行が正常に完了したことを検証してください。ダークサイト向け NetApp Backup and Recovery は、ONTAP ボリュームワークロードのみをサポートします。

ONTAP ボリュームワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recoveryを使用したONTAPボリューム保護について説明します"]を参照してください。



[[kubernetes-workloads-enhancements]]
=== Kubernetes ワークロードの機能強化

今回のリリースでは、Kubernetesワークロードに以下の機能強化が導入されました。

* *Trident Protect 26.09*：このリリースには Trident Protect 26.09 が含まれます。
* *クラスタおよび名前空間単位のロールベースアクセス制御（RBAC）*：Kubernetesクラスタの検出中に、新しいクラスタに関連付けるプロジェクトまたはフォルダを選択することで、リソースへのアクセスを制御できます。アクセス制御のために、特定の名前空間を登録することもできます。これにより、クラスタレベルまたは名前空間レベルで、よりきめ細かなアクセス制御が可能になります。
* *ファイルとフォルダの復元*：Kubernetes VM ベースのアプリケーションバックアップから、特定のファイルとフォルダを復元またはダウンロードできるようになりました。


Kubernetesワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["NetApp Backup and Recoveryを使用したKubernetesワークロードの保護について説明します"]を参照してください。
