= 一般的なNetApp Backup and Recoveryの機能強化
:allow-uri-read: 




[[general-netapp-backup-and-recovery-enhancement]]
=== 一般的なNetApp Backup and Recoveryの機能強化

今回のリリースでは、KVM、Hyper-V、およびVMwareワークロードに以下の機能強化が導入されました：

*コンソールロールベースアクセス制御（RBAC）サポート*：Hyper-V、KVM、VMware ワークロードは、RBAC 向け NetApp Console フレームワークをサポートするようになり、個々の Hyper-V、KVM、または VMware ホストへのアクセスを管理できます。

https://docs.netapp.com/us-en/data-services-backup-recovery/br-rbac-setup.html["RBACの使用方法について詳しくは、NetApp Backup and Recoveryを参照してください"]。



[[ontap-volumes-workloads-enhancement]]
=== ONTAPボリュームワークロードの強化

今回のリリースでは、ONTAP Volumes ワークロードに、以下のプレビュー版機能強化が導入されました。

*Cloud Volumes ONTAP Azure Entra ID のサポート*：Azure 認証にストレージアカウントのアクセスキーを使用しない場合は、Azure オブジェクトストレージバケット構成に Microsoft Entra ID 認証を使用できるようになりました。このオプションは、ONTAP 9.16.1以降を実行しているAzureシステム内のCloud Volumes ONTAPでサポートされています。

ONTAP ボリュームワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recoveryを使用したONTAPボリューム保護について説明します"]を参照してください。



[[vmware-workloads-enhancement]]
=== VMwareワークロードの機能強化

今回のリリースでは、VMwareワークロードに以下の機能強化が導入されました。

*Google Cloud NetApp Volumes Flex Unified のサポート*：NetApp Backup and Recovery for VMware ワークロードが、Google Cloud NetApp Volumes の Flex Unified サービスレベルをサポートするようになりました。Flex Unified は ONTAP モードでのみサポートされています。

VMwareワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["VMwareワークロードをNetApp Backup and Recoveryで保護する"]を参照してください。
